(function(){
  "use strict";
  const SESSION_KEY="tb_talkflow_member_session_v1",$=selector=>document.querySelector(selector),esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  let session=sessionStorage.getItem(SESSION_KEY)||"",topics=[],progressByDate={},cursor=new Date(),activeDate="";
  const localFixture=()=>["localhost","127.0.0.1"].includes(location.hostname)&&new URLSearchParams(location.search).get("fixtures")==="1";
  function monthKey(){return`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}`}
  function titleOf(topic){return topic?.title&&typeof topic.title==="object"?topic.title: {en:topic?.title||"",ko:""}}
  function categoryOf(topic){return topic?.category&&typeof topic.category==="object"?topic.category.en||topic.category.ko||"":topic?.category||""}
  function cleanStoryLine(value){return String(value||"").replace(/\s+(?:Key details|핵심 정보)\s*:[\s\S]*$/i,"").trim()}
  function normalizeMemberKo(value){return String(value||"").replace(/PRIVATE CARD/gi,"비밀 카드").replace(/평결문을 써요\.?/g,"우리 팀의 최종 선택과 이유를 적으세요.").replace(/평결을 써요\.?/g,"우리 팀의 최종 선택과 이유를 적으세요.").replace(/평결문/g,"최종 선택과 이유").replace(/평결/g,"최종 선택").replace(/우리 그룹의 결론/g,"우리 팀의 선택").replace(/우리 그룹/g,"우리 팀")}
  async function jsonRequest(url,options={}){const response=await fetch(url,{...options,headers:{"content-type":"application/json",...(options.headers||{})}}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||"요청을 처리하지 못했습니다.");return payload}
  async function login(credentials){const payload=await jsonRequest("/api/talkflow/member-login",{method:"POST",headers:{"x-talkflow-request":"app"},body:JSON.stringify(credentials)});session=payload.token;sessionStorage.setItem(SESSION_KEY,session);return payload}
  async function loadTopics(){if(localFixture()){const topic=await fetch("/talkflow/fixtures/member-topic.json").then(response=>response.json());cursor=new Date(`${topic.date.slice(0,7)}-01T12:00:00`);topics=[topic];return}const payload=await jsonRequest(`/api/talkflow/member-topics?month=${encodeURIComponent(monthKey())}`,{headers:{"x-talkflow-member-session":session}});topics=payload.topics||[]}
  async function loadProgress(){if(localFixture()){progressByDate=JSON.parse(localStorage.getItem("tb_topic_progress_fixture")||"{}");return}const payload=await jsonRequest(`/api/talkflow/member-progress?month=${encodeURIComponent(monthKey())}`,{headers:{"x-talkflow-member-session":session}});progressByDate=Object.fromEntries((payload.progress||[]).map(item=>[item.date,item]))}
  async function saveProgress(date,reflection){if(localFixture()){const now=new Date().toISOString(),previous=progressByDate[date];progressByDate[date]={date,reflection,completedAt:previous?.completedAt||now,updatedAt:now};localStorage.setItem("tb_topic_progress_fixture",JSON.stringify(progressByDate));return progressByDate[date]}const payload=await jsonRequest("/api/talkflow/member-progress",{method:"POST",headers:{"x-talkflow-request":"app","x-talkflow-member-session":session},body:JSON.stringify({date,reflection})});return payload.progress}
  function questionRows(items){return`<div class="question-list">${(items||[]).map((item,index)=>`<div class="question-row"><b>${String(index+1).padStart(2,"0")}</b><p>${esc(item.en||item.questionEn||item.question||"")}${item.ko?`<span lang="ko">${esc(item.ko)}</span>`:""}</p></div>`).join("")}</div>`}
  function section(title,body){return body?`<section class="topic-section"><h3>${title}</h3>${body}</section>`:""}
  function wordList(items){return `<div class="topic-word-list">${(items||[]).map(item=>`<span><strong>${esc(item.en)}</strong><small lang="ko">${esc(item.ko)}</small></span>`).join("")}</div>`}
  function expressionRows(items){return `<div class="topic-expression-list">${(items||[]).map(item=>`<p><strong>${esc(item.en)}</strong><span lang="ko">${esc(item.ko)}</span></p>`).join("")}</div>`}
  function renderV4Topic(topic){const title=titleOf(topic),one=topic.page1||{},two=topic.page2||{},story=one.story||{},talk=(title,action,items,extra="")=>`<section class="topic-section topic-mockup-talk"><h3>${title}</h3><p class="section-action">${action}</p>${extra}${questionRows((items||[]).map(en=>({en})))}</section>`;return `<header class="topic-hero topic-mockup-header"><span>THEBOX</span><b>${esc(categoryOf(topic))}</b><time>${esc(topic.date)}</time><h2>${esc(title.en)}</h2></header><p class="topic-seat-rule"><strong>Closest birthday is #1. Continue clockwise.</strong><span lang="ko">생일이 오늘과 가장 가까운 사람이 #1입니다. 이후 시계 방향으로 번호를 정하세요.</span></p><section class="topic-section topic-mockup-story"><h3>TODAY'S STORY</h3><p class="section-action">Read aloud. Vote without reasons.</p><div class="story topic-v4-story"><p>${esc(story.en||"")}</p></div><h4>KEY WORDS</h4>${wordList(one.keyWords)}<div class="topic-mockup-vote"><h4>QUICK VOTE</h4><div><p class="vote-question">${esc(one.quickVote?.question||"")}</p><div class="vote-options">${(one.quickVote?.options||[]).map((option,index)=>`<span><b>${index+1}</b>${esc(option)}</span>`).join("")}</div></div></div></section><div class="topic-talk-grid">${talk("EASY TALK","Ask & Pass. Pick the next speaker.",one.easyTalk)}${talk("REAL TALK","Ask & Pass. Reveal one number together.",one.realTalk,'<p class="topic-culture">CULTURE SWAP · Start with ‘In my country or workplace…’</p>')}</div>${section("TODAY’S ENGLISH",expressionRows(one.todayEnglish))}${section("STORY 해석",`<p class="story-translation" lang="ko">${esc(story.ko||"")}</p>`)}<div class="topic-page-break" aria-hidden="true"></div><header class="topic-round-header"><time>${esc(topic.date)}</time><h2>Round Two</h2></header><p class="topic-seat-rule"><strong>New table, new people. Re-number 1–N by shoe size — smallest goes first.</strong><span lang="ko">→ 그룹이 바뀌었으니 신발 사이즈로 새로 번호를 정하세요. 가장 작은 사람이 1번.</span></p>${section("RANDOM QUESTIONS",`<p class="section-action">Ask & Pass. Pick the next speaker.</p>${questionRows(two.randomQuestions||[])}`)}${section("RANDOM WORDS",`<p class="section-action">Pick any word. Say what it makes you think of, and why.</p>${wordList(two.randomWords)}`)}${renderCompletion(topic)}`}
  function renderCompletion(topic){const saved=progressByDate[topic.date],value=saved?.reflection||"";return`<section class="topic-completion" aria-labelledby="completion-title"><p class="eyebrow">MY TOPIC NOTE</p><h3 id="completion-title">오늘의 한 줄</h3><p>가장 기억에 남은 생각을 한 줄로 남기면 읽음 기록이 저장됩니다.</p><form id="member-completion-form"><label for="member-reflection">나의 한 줄</label><textarea id="member-reflection" maxlength="500" rows="3" placeholder="예: 선물에서는 가격보다 상대방을 이해하는 마음이 더 중요하다고 생각했다.">${esc(value)}</textarea><div class="completion-actions"><span id="member-reflection-count">${value.length}/500</span><button class="primary-button" type="submit">${saved?"기록 수정하기":"읽었어요 · 기록하기"}</button></div><p id="member-completion-status" class="completion-status" role="status">${saved?`저장됨 · ${esc(formatDate(saved.updatedAt))}`:""}</p></form></section>`}
  function renderTopic(topic){if(!topic)return`<div class="empty-topic"><strong>이 달에 공개된 토픽이 없습니다.</strong><p>관리자가 토픽을 공개하면 여기에 표시됩니다.</p></div>`;if(topic.topicVersion==="topic-v4")return renderV4Topic(topic);const title=titleOf(topic),one=topic.session1||{},two=topic.session2||{},story=one.story||{},activity=two.activity||{},expressions=one.expressions||[],storyText=(story.en||[]).map(cleanStoryLine).filter(Boolean).join(" ");return`<header class="topic-hero"><time>${esc(topic.date)}</time><h2>${esc(title.en)}</h2><p>${esc(title.ko)}</p></header>${section("TODAY’S STORY",`<div class="story"><p>${esc(storyText)}</p></div>`)}${section("EASY TALK",questionRows(one.easyTalk))}${section("REAL TALK",questionRows(one.realTalk))}${section("TODAY’S ENGLISH",`<div class="expression-list">${expressions.map(item=>`<p>${esc(item.en||item)}</p>`).join("")}</div>`)}${section("TODAY’S ACTIVITY",`<h4 class="activity-title">${esc(activity.name||"")}</h4><p class="activity-intro">${esc(normalizeMemberKo(activity.instructionKo||""))}</p><div class="materials">${(activity.materials||[]).map(item=>`<div class="material">${esc(item.en||item)}</div>`).join("")}</div><ol class="steps">${(activity.stepsKo||[]).map((step,index)=>`<li class="step"><b>${String(index+1).padStart(2,"0")}</b><span>${esc(normalizeMemberKo(step))}</span></li>`).join("")}</ol>`)}${section("GROUP RESULT",two.groupResult?`<div class="group-result"><strong>${esc(two.groupResult.en)}</strong><span>${esc(normalizeMemberKo(two.groupResult.ko))}</span></div>`:"")}${section("THINK HARDER",questionRows(two.thinkHarder?[two.thinkHarder]:[]))}${section("FINAL QUESTION",questionRows(two.finalQuestion?[two.finalQuestion]:[]))}${renderCompletion(topic)}`}
  function formatDate(value){if(!value)return"";const date=new Date(value);return Number.isNaN(date.valueOf())?"":new Intl.DateTimeFormat("ko-KR",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(date)}
  function renderHistory(){const records=Object.values(progressByDate).sort((a,b)=>b.date.localeCompare(a.date));$("#member-history-count").textContent=`${records.length}개 완료`;$("#member-history-list").innerHTML=records.length?records.map(record=>{const topic=topics.find(item=>item.date===record.date),title=titleOf(topic);return`<button type="button" data-history-date="${esc(record.date)}"><span><b>${esc(record.date.slice(5).replace("-","."))}</b>${esc(title.en||"공개 토픽")}</span><small>${esc(record.reflection)}</small></button>`}).join(""):`<p>아직 저장한 기록이 없습니다.</p>`;document.querySelectorAll("[data-history-date]").forEach(button=>button.onclick=()=>{activeDate=button.dataset.historyDate;render();$("#topic").focus()})}
  function bindCompletion(topic){const form=$("#member-completion-form");if(!form||!topic)return;const input=$("#member-reflection"),count=$("#member-reflection-count"),status=$("#member-completion-status");input.oninput=()=>count.textContent=`${input.value.length}/500`;form.onsubmit=async event=>{event.preventDefault();const button=event.submitter,value=input.value.trim();if(!value){status.textContent="한 줄 기록을 입력해 주세요.";input.focus();return}button.disabled=true;button.textContent="저장 중…";status.textContent="";try{const saved=await saveProgress(topic.date,value);progressByDate[topic.date]=saved;render()}catch(cause){status.textContent=cause.message;button.disabled=false;button.textContent=progressByDate[topic.date]?"기록 수정하기":"읽었어요 · 기록하기"}}}
  function render(){const signedIn=Boolean(session)||localFixture();$("#member-login-view").hidden=signedIn;$("#member-topic-view").hidden=!signedIn;$("#member-logout").hidden=!signedIn||localFixture();if(!signedIn)return;$("#member-month-label").textContent=`${cursor.getFullYear()}년 ${cursor.getMonth()+1}월`;$("#member-date-list").innerHTML=topics.map(topic=>{const complete=Boolean(progressByDate[topic.date]);return`<button type="button" class="${complete?"is-complete":""}" data-member-date="${esc(topic.date)}" aria-current="${topic.date===activeDate?"date":"false"}" aria-label="${Number(topic.date.slice(8))}일${complete?", 읽음 기록 완료":""}">${complete?"✓ ":""}${Number(topic.date.slice(8))}일</button>`}).join("");const topic=topics.find(item=>item.date===activeDate);$("#topic").innerHTML=renderTopic(topic);renderHistory();bindCompletion(topic);document.querySelectorAll("[data-member-date]").forEach(button=>button.onclick=()=>{activeDate=button.dataset.memberDate;render();$("#topic").focus()})}
  async function refresh(){await loadTopics();await loadProgress();if(!topics.some(topic=>topic.date===activeDate))activeDate=topics.at(-1)?.date||"";render()}
  $("#member-login-form").onsubmit=async event=>{event.preventDefault();const button=event.submitter,error=$("#member-login-error");button.disabled=true;error.hidden=true;try{await login({name:$("#member-name").value.trim(),phone:$("#member-phone").value.replace(/\D/g,""),birth:$("#member-birth").value.replace(/\D/g,"")});await refresh()}catch(cause){error.textContent=cause.message;error.hidden=false}finally{button.disabled=false}};
  $("#member-logout").onclick=()=>{session="";sessionStorage.removeItem(SESSION_KEY);topics=[];progressByDate={};activeDate="";render()};
  $("#member-prev-month").onclick=async()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);await refresh()};$("#member-next-month").onclick=async()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);await refresh()};
  window.TalkFlowMember={renderTopic,titleOf,categoryOf,cleanStoryLine,normalizeMemberKo};
  if(session||localFixture())refresh().catch(()=>{session="";sessionStorage.removeItem(SESSION_KEY);render()});else render();
})();
