(function(){
  "use strict";
  const SESSION_KEY="tb_talkflow_member_session_v1",$=selector=>document.querySelector(selector),esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  let session=sessionStorage.getItem(SESSION_KEY)||"",topics=[],cursor=new Date(),activeDate="";
  const localFixture=()=>["localhost","127.0.0.1"].includes(location.hostname)&&new URLSearchParams(location.search).get("fixtures")==="1";
  function monthKey(){return`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}`}
  function titleOf(topic){return topic?.title&&typeof topic.title==="object"?topic.title: {en:topic?.title||"",ko:""}}
  function cleanStoryLine(value){return String(value||"").replace(/\s+(?:Key details|핵심 정보)\s*:[\s\S]*$/i,"").trim()}
  function normalizeMemberKo(value){return String(value||"").replace(/PRIVATE CARD/gi,"비밀 카드").replace(/평결문을 써요\.?/g,"우리 팀의 최종 선택과 이유를 적으세요.").replace(/평결을 써요\.?/g,"우리 팀의 최종 선택과 이유를 적으세요.").replace(/평결문/g,"최종 선택과 이유").replace(/평결/g,"최종 선택").replace(/우리 그룹의 결론/g,"우리 팀의 선택").replace(/우리 그룹/g,"우리 팀")}
  async function jsonRequest(url,options={}){const response=await fetch(url,{...options,headers:{"content-type":"application/json",...(options.headers||{})}}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||"요청을 처리하지 못했습니다.");return payload}
  async function login(credentials){const payload=await jsonRequest("/api/talkflow/member-login",{method:"POST",headers:{"x-talkflow-request":"app"},body:JSON.stringify(credentials)});session=payload.token;sessionStorage.setItem(SESSION_KEY,session);return payload}
  async function loadTopics(){if(localFixture()){const topic=await fetch("/talkflow/fixtures/member-topic.json").then(response=>response.json());cursor=new Date(`${topic.date.slice(0,7)}-01T12:00:00`);topics=[topic];return}const payload=await jsonRequest(`/api/talkflow/member-topics?month=${encodeURIComponent(monthKey())}`,{headers:{"x-talkflow-member-session":session}});topics=payload.topics||[]}
  function questionRows(items){return`<div class="question-list">${(items||[]).map((item,index)=>`<div class="question-row"><b>${String(index+1).padStart(2,"0")}</b><p>${esc(item.en||item.questionEn||item.question||"")}</p></div>`).join("")}</div>`}
  function section(title,body){return body?`<section class="topic-section"><h3>${title}</h3>${body}</section>`:""}
  function renderTopic(topic){if(!topic)return`<div class="empty-topic"><strong>이 달에 공개된 토픽이 없습니다.</strong><p>관리자가 토픽을 공개하면 여기에 표시됩니다.</p></div>`;const title=titleOf(topic),one=topic.session1||{},two=topic.session2||{},story=one.story||{},activity=two.activity||{},expressions=one.expressions||[],storyText=(story.en||[]).map(cleanStoryLine).filter(Boolean).join(" ");return`<header class="topic-hero"><time>${esc(topic.date)}</time><h2>${esc(title.en)}</h2><p>${esc(title.ko)}</p></header>${section("TODAY’S STORY",`<div class="story"><p>${esc(storyText)}</p></div>`)}${section("EASY TALK",questionRows(one.easyTalk))}${section("REAL TALK",questionRows(one.realTalk))}${section("TODAY’S ENGLISH",`<div class="expression-list">${expressions.map(item=>`<p>${esc(item.en||item)}</p>`).join("")}</div>`)}${section("TODAY’S ACTIVITY",`<h4 class="activity-title">${esc(activity.name||"")}</h4><p class="activity-intro">${esc(normalizeMemberKo(activity.instructionKo||""))}</p><div class="materials">${(activity.materials||[]).map(item=>`<div class="material">${esc(item.en||item)}</div>`).join("")}</div><ol class="steps">${(activity.stepsKo||[]).map((step,index)=>`<li class="step"><b>${String(index+1).padStart(2,"0")}</b><span>${esc(normalizeMemberKo(step))}</span></li>`).join("")}</ol>`)}${section("GROUP RESULT",two.groupResult?`<div class="group-result"><strong>${esc(two.groupResult.en)}</strong><span>${esc(normalizeMemberKo(two.groupResult.ko))}</span></div>`:"")}${section("THINK HARDER",questionRows(two.thinkHarder?[two.thinkHarder]:[]))}${section("FINAL QUESTION",questionRows(two.finalQuestion?[two.finalQuestion]:[]))}`}
  function render(){const signedIn=Boolean(session)||localFixture();$("#member-login-view").hidden=signedIn;$("#member-topic-view").hidden=!signedIn;$("#member-logout").hidden=!signedIn||localFixture();if(!signedIn)return;$("#member-month-label").textContent=`${cursor.getFullYear()}년 ${cursor.getMonth()+1}월`;$("#member-date-list").innerHTML=topics.map(topic=>`<button type="button" data-member-date="${esc(topic.date)}" aria-current="${topic.date===activeDate?"date":"false"}">${Number(topic.date.slice(8))}일</button>`).join("");$("#topic").innerHTML=renderTopic(topics.find(topic=>topic.date===activeDate));document.querySelectorAll("[data-member-date]").forEach(button=>button.onclick=()=>{activeDate=button.dataset.memberDate;render();$("#topic").focus()})}
  async function refresh(){await loadTopics();if(!topics.some(topic=>topic.date===activeDate))activeDate=topics.at(-1)?.date||"";render()}
  $("#member-login-form").onsubmit=async event=>{event.preventDefault();const button=event.submitter,error=$("#member-login-error");button.disabled=true;error.hidden=true;try{await login({name:$("#member-name").value.trim(),phone:$("#member-phone").value.replace(/\D/g,""),birth:$("#member-birth").value.replace(/\D/g,"")});await refresh()}catch(cause){error.textContent=cause.message;error.hidden=false}finally{button.disabled=false}};
  $("#member-logout").onclick=()=>{session="";sessionStorage.removeItem(SESSION_KEY);topics=[];activeDate="";render()};
  $("#member-prev-month").onclick=async()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);await refresh()};$("#member-next-month").onclick=async()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);await refresh()};
  window.TalkFlowMember={renderTopic,titleOf,cleanStoryLine,normalizeMemberKo};
  if(session||localFixture())refresh().catch(()=>{session="";sessionStorage.removeItem(SESSION_KEY);render()});else render();
})();
