import {createRequire} from "node:module";
import {createServer} from "node:http";
import {mkdir,readFile} from "node:fs/promises";
import {existsSync} from "node:fs";
import {extname,join,normalize} from "node:path";
import {homedir} from "node:os";

const require=createRequire(import.meta.url);let playwright;try{playwright=require("playwright")}catch{playwright=createRequire(join(homedir(),".cache","codex-runtimes","codex-primary-runtime","dependencies","node","node_modules","playwright","index.js"))("playwright")}
const {chromium}=playwright,root=new URL(".",import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,"$1"),mime={".html":"text/html; charset=utf-8",".css":"text/css",".js":"text/javascript"};
const server=createServer(async(request,response)=>{try{const pathname=new URL(request.url,"http://localhost").pathname,path=normalize(join(root,pathname==="/"?"index.html":pathname.slice(1)));if(!path.startsWith(normalize(root)))throw new Error("invalid path");response.setHeader("Content-Type",mime[extname(path)]||"application/octet-stream");response.end(await readFile(path))}catch{response.statusCode=404;response.end("Not found")}});await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
const systemChrome="C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",browser=await chromium.launch({headless:true,...(existsSync(systemChrome)?{executablePath:systemChrome}:{})}),checks=[],check=(name,value,detail="")=>{checks.push({name,pass:Boolean(value),detail});if(!value)throw new Error(`${name}: ${detail}`)};
try{const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage(),calls=[];page.on("request",request=>{if(/api\.anthropic\.com|api\.github\.com/.test(request.url()))calls.push(request.url())});await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:"networkidle"});const initialData=await page.evaluate(()=>localStorage.getItem("tb_talkflow_v1"));
check("default route is tasks",new URL(page.url()).searchParams.get("view")==="tasks"&&await page.locator(".task-home").isVisible(),page.url());check("task list has at most eight items",await page.locator(".task-list>.task-row").count()<=8);check("rows expose at most one primary action",await page.locator(".task-row").evaluateAll(rows=>rows.every(row=>row.querySelectorAll(".row-primary button,.row-primary a").length<=1)));check("this week is separate",await page.locator(".this-week").isVisible());
await page.getByRole("button",{name:"전체 월",exact:true}).click();check("month route pushed",new URL(page.url()).searchParams.get("view")==="month"&&await page.locator(".compact-month").isVisible(),page.url());const monthUrl=page.url();await page.locator(".month-row").first().click();check("drawer date route",new URL(page.url()).searchParams.get("tab")==="review"&&await page.locator(".date-drawer").isVisible(),page.url());const detailUrl=page.url();await page.getByRole("button",{name:"학생용",exact:true}).click();check("student route pushed",new URL(page.url()).searchParams.get("tab")==="student"&&new URL(page.url()).searchParams.get("page")==="1",page.url());await page.locator(".route-page-switch [data-preview-page='2']").click();const pageTwoUrl=page.url();check("student page two pushed",new URL(pageTwoUrl).searchParams.get("page")==="2",pageTwoUrl);await page.goBack();check("back restores student page one",new URL(page.url()).searchParams.get("page")==="1",page.url());await page.goBack();check("back restores review drawer",page.url()===detailUrl&&await page.locator(".date-drawer").isVisible(),page.url());await page.goBack();check("back restores compact month",page.url()===monthUrl&&await page.locator(".compact-month").isVisible(),page.url());await page.goBack();check("back restores tasks",new URL(page.url()).searchParams.get("view")==="tasks"&&await page.locator(".task-home").isVisible(),page.url());await page.goForward();check("forward restores month",await page.locator(".compact-month").isVisible());await page.goForward();check("forward restores drawer",await page.locator(".date-drawer").isVisible());await page.goForward();check("forward restores student page one",new URL(page.url()).searchParams.get("page")==="1");await page.goForward();check("forward restores student page two",page.url()===pageTwoUrl);await page.reload({waitUntil:"networkidle"});check("reload restores student page two",new URL(page.url()).searchParams.get("page")==="2"&&new URL(page.url()).searchParams.get("tab")==="student");
await page.goto(`http://127.0.0.1:${server.address().port}/?section=topics&view=calendar&month=2026-08&date=bad&tab=wat&page=9`,{waitUntil:"networkidle"});const normalized=new URL(page.url());check("invalid route normalized",normalized.searchParams.get("view")==="calendar"&&!normalized.searchParams.has("date")&&!normalized.searchParams.has("tab")&&!normalized.searchParams.has("page"),page.url());check("calendar has no internal work buttons",await page.locator(".simple-month-grid [data-action],.simple-month-grid [data-open],.simple-month-grid [data-custom-date],.simple-month-grid [data-auto-date]").count()===0);const drawerTrigger=page.locator(".simple-calendar-cell:not([disabled])").first(),drawerTriggerDate=await drawerTrigger.getAttribute("data-drawer-date");await drawerTrigger.click();await page.locator(".date-drawer [aria-label='닫기']").click();await page.locator(".date-drawer").waitFor({state:"detached"});check("drawer close clears route",!new URL(page.url()).searchParams.has("date")&&!new URL(page.url()).searchParams.has("tab"),page.url());await page.waitForFunction(date=>document.activeElement?.getAttribute("data-drawer-date")===date,drawerTriggerDate);check("drawer close restores row focus",await page.evaluate(date=>document.activeElement?.getAttribute("data-drawer-date")===date,drawerTriggerDate));await page.setViewportSize({width:375,height:600});await page.goto(`http://127.0.0.1:${server.address().port}/?section=topics&view=month&month=2026-08`,{waitUntil:"networkidle"});await page.evaluate(()=>scrollTo(0,Math.min(300,document.documentElement.scrollHeight-innerHeight)));const savedScroll=await page.evaluate(()=>scrollY);await page.evaluate(()=>document.querySelector(".month-row")?.click());await page.goBack();await page.waitForFunction(expected=>Math.abs(scrollY-expected)<=2,savedScroll);const restoredScroll=await page.evaluate(()=>scrollY);check("month scroll restored",Math.abs(restoredScroll-savedScroll)<=2,`${savedScroll} -> ${restoredScroll}`);check("history restoration triggers no external calls",calls.length===0,JSON.stringify(calls));check("history restoration does not save topics",await page.evaluate(()=>localStorage.getItem("tb_talkflow_v1"))===initialData);check("secret params absent",![...new URL(page.url()).searchParams.keys()].some(key=>/key|token|gist|prompt/i.test(key)),page.url());
await page.goto(`http://127.0.0.1:${server.address().port}/?section=settings&panel=ai`,{waitUntil:"networkidle"});check("settings exposes five focused sections",await page.locator("[data-settings-section]").count()===5);for(const panel of ["ai","gist","schedule","print","data"]){await page.locator(`[data-settings-section='${panel}']`).click();check(`settings ${panel} route`,new URL(page.url()).searchParams.get("panel")===panel&&await page.locator(`[data-settings-panel='${panel}']:not([hidden])`).count()>=1,page.url())}
await page.goto(`http://127.0.0.1:${server.address().port}/?section=print`,{waitUntil:"networkidle"});await page.getByRole("button",{name:"전체 선택"}).click();await page.locator("[name='print-role'][value='combined']").check();const selectedCount=await page.locator("[data-print-date]:checked").count();check("combined print calculates four pages per topic",await page.getByText(`${selectedCount}개 토픽 · ${selectedCount*4}페이지`,{exact:true}).count()===1);await page.getByRole("button",{name:`${selectedCount*4}페이지 미리보기`}).click();check("combined preview renders student and leader pages",await page.locator(".a4-page").count()===selectedCount*4);
const evidence=join(root,"..",".omo","evidence","task-home-history","final");await mkdir(evidence,{recursive:true});
for(const width of [375,768,1280,1600]){await page.setViewportSize({width,height:900});await page.goto(`http://127.0.0.1:${server.address().port}/?section=topics&view=tasks&month=2026-08`,{waitUntil:"networkidle"});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);check(`${width}px overflow 0`,overflow<=1,String(overflow));await page.screenshot({path:join(evidence,`tasks-${width}.png`),fullPage:true});await page.goto(`http://127.0.0.1:${server.address().port}/?section=topics&view=calendar&month=2026-08`,{waitUntil:"networkidle"});await page.screenshot({path:join(evidence,`calendar-${width}.png`),fullPage:true});await page.goto(`http://127.0.0.1:${server.address().port}/?section=print`,{waitUntil:"networkidle"});await page.screenshot({path:join(evidence,`batch-${width}.png`),fullPage:true})}
await page.setViewportSize({width:375,height:900});await page.goto(`http://127.0.0.1:${server.address().port}/?section=topics&view=month&month=2026-08`,{waitUntil:"networkidle"});const mobileTrigger=page.locator(".month-row").first();await mobileTrigger.focus();await page.keyboard.press("Enter");check("mobile drawer opens from keyboard",await page.locator(".date-drawer").isVisible());await page.screenshot({path:join(evidence,"drawer-375.png"),fullPage:true});await page.keyboard.press("Escape");await page.waitForFunction(()=>document.activeElement?.matches(".month-row"));check("Escape closes drawer and restores focus",await page.locator(".date-drawer").count()===0);await page.goto(`http://127.0.0.1:${server.address().port}/?section=settings&panel=data`,{waitUntil:"networkidle"});await page.screenshot({path:join(evidence,"settings-data-375.png"),fullPage:true});
console.log(`navigation-qa: PASS (${checks.length} checks)`)}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
