(function () {
  "use strict";
  const dates = ["2026-08-03","2026-08-06","2026-08-10","2026-08-13","2026-08-17","2026-08-20","2026-08-24","2026-08-27"];
  const specs = [
    {
      title:["Can You Trust the Stars?","별점을 믿을 수 있을까?"],category:"shopping",
      hook:["You are choosing a restaurant you have never visited. One place has thousands of five-star reviews, while another has only twenty detailed reviews. Some comments sound genuine, but others feel copied. You have ten minutes to decide.","처음 가는 식당을 고르고 있습니다. 한 곳은 별점 5점 리뷰가 수천 개이고, 다른 곳은 자세한 리뷰가 스무 개뿐입니다. 어떤 댓글은 진짜 같지만 다른 댓글은 복사한 것처럼 보입니다. 결정할 시간은 10분입니다."],
      goal:["Explain what makes online information feel trustworthy and make a practical choice.","온라인 정보가 믿을 만하다고 느끼는 기준을 설명하고 현실적인 선택을 해 봅니다."],
      small:[["What is the last thing you checked reviews for?","최근 무엇을 사거나 고르기 전에 리뷰를 확인했나요?"],["Which do you check first: stars, photos, or comments?","별점, 사진, 댓글 중 무엇을 먼저 확인하나요?"],["Would you trust a review with no photo?","사진 없는 리뷰를 믿을 수 있나요?"]],
      quick:["ranking","Trust Signal Ranking","신뢰 신호 순위 정하기","Rank these from most to least useful. Give one reason for your top choice.","가장 유용한 것부터 순위를 정하고 1위의 이유를 말하세요.",["Recent reviews","Customer photos","Detailed negatives","Verified purchase","Reviewer history"]],
      easy:[["How do you usually read reviews?","보통 리뷰를 어떻게 읽나요?","I usually start with...","What do you check next?"],["What makes you stop trusting a review?","어떤 리뷰를 보면 신뢰가 사라지나요?","I get suspicious when...","Is that always a warning sign?"],["Would you choose a lower-rated place?","평점이 더 낮은 곳을 고를 수 있나요?","I might choose it if...","What extra information would help?"]],
      main:[["What makes a review feel trustworthy to you?","어떤 리뷰가 신뢰할 만하게 느껴지나요?","I trust a review more when...","Can you remember a review that changed your mind?","Can many similar reviews create false trust?"],["Should platforms remove reviews they suspect are fake?","플랫폼은 가짜로 의심되는 리뷰를 삭제해야 할까요?","Platforms should...","What evidence should they require?","How can they avoid deleting honest opinions?"],["Are negative reviews more useful than positive ones?","부정적인 리뷰가 긍정적인 리뷰보다 더 유용한가요?","Negative reviews are useful because...","What kind of complaint helps you decide?","Can negativity make a good product look unfairly bad?"],["Who is responsible when a review leads to a bad choice?","리뷰 때문에 잘못 선택했을 때 책임은 누구에게 있을까요?","The main responsibility belongs to...","What should the customer check personally?","What could make responsibility shared?"]],
      mid:["detective","Review Detective","리뷰 탐정","Choose the two most believable comments and identify the detail that earns your trust.","가장 믿을 만한 댓글 두 개를 고르고 신뢰를 주는 세부 정보를 찾으세요.",["Amazing! Best ever!","The soup was hot, but the wait was 25 minutes.","Five stars. Five stars. Five stars.","I visited at lunch; the set menu was filling, though the tables were close.","Not good.","Staff solved our order mistake quickly."]],
      phrases:[["I take that rating with a grain of salt.","그 평점은 어느 정도 걸러서 봐요.","When a score may be misleading"],["The details make it sound credible.","세부 내용 때문에 믿을 만하게 들려요.","When a review includes specific evidence"],["That would be a deal-breaker for me.","그건 저라면 선택하지 않을 결정적 이유예요.","When one problem changes your decision"]],
      final:["Name one review clue you will pay more attention to next time.","다음부터 더 주의 깊게 볼 리뷰의 단서 한 가지를 말해 보세요.","Next time, I’ll pay more attention to..."]
    },
    {
      title:["The Delivery Dinner Dilemma","배달 저녁 메뉴의 딜레마"],category:"lifestyle",
      hook:["Four friends are ordering dinner after a long day. One wants something healthy, one wants comfort food, one has a small budget, and one hates waiting. Every restaurant solves only two of those problems. The group must place one order.","긴 하루를 보낸 친구 네 명이 저녁을 주문하려고 합니다. 한 명은 건강한 음식, 한 명은 위로가 되는 음식, 한 명은 저렴한 음식, 한 명은 빠른 배달을 원합니다. 모든 식당은 그중 두 가지만 만족시킵니다. 한 번의 주문으로 결정해야 합니다."],
      goal:["Negotiate different priorities and reach one food-delivery decision.","서로 다른 우선순위를 조율해 하나의 배달 메뉴를 결정합니다."],
      small:[["What food travels well for delivery?","배달해도 맛이 잘 유지되는 음식은 무엇인가요?"],["How long is too long to wait?","배달을 얼마나 기다리면 너무 길다고 느끼나요?"],["Do you reorder favorites or try new places?","늘 먹던 곳에서 주문하나요, 새 식당을 시도하나요?"]],
      quick:["eitherOr","Fast Choice","빠른 선택","Choose one in each pair and explain just one choice.","각 쌍에서 하나를 고르고 한 가지 선택만 이유를 말하세요.",["Fast or fresh","Cheap or generous portions","One shared dish or separate meals","Familiar or new"]],
      easy:[["What makes delivery worth the extra cost?","추가 비용을 내고도 배달할 가치가 있는 때는 언제인가요?","Delivery feels worth it when...","What cost feels reasonable?"],["How do you choose when a group cannot agree?","여럿이 메뉴에 합의하지 못하면 어떻게 고르나요?","Our group usually...","Does that method feel fair?"],["What is one food you would never order for delivery?","절대 배달로 주문하지 않을 음식은 무엇인가요?","I would avoid ordering...","Would better packaging change your mind?"]],
      main:[["Should everyone compromise equally in a group order?","단체 주문에서는 모두가 똑같이 양보해야 할까요?","A fair compromise would be...","What if one person has a dietary restriction?","When is an unequal compromise actually fairer?"],["Is convenience changing the way people value food?","편리함이 사람들이 음식의 가치를 판단하는 방식을 바꾸고 있나요?","Convenience makes people...","How has your own routine changed?","What might be lost when speed becomes the priority?"],["Who should pay when fees make a group order expensive?","수수료 때문에 단체 주문이 비싸지면 누가 부담해야 할까요?","The fairest way to split it is...","Should the person who chose the restaurant pay more?","Could a perfectly equal split still feel unfair?"],["What should delivery apps improve first?","배달 앱이 가장 먼저 개선해야 할 것은 무엇인가요?","The first improvement should be...","How would customers notice the change?","Would that improvement create a new problem?"]],
      mid:["rolePick","One Order, Four Needs","한 번의 주문, 네 가지 요구","Pick a role. Pitch one restaurant, then agree on a single order within five minutes.","역할을 하나 고르세요. 식당 하나를 제안한 뒤 5분 안에 한 주문으로 합의하세요.",["Healthy eater","Budget keeper","Hungry now","Adventurous eater"]],
      phrases:[["Can we meet halfway on this?","이 부분에서 서로 절충할 수 있을까요?","When priorities conflict"],["That gives us the best of both worlds.","그렇게 하면 두 가지 장점을 모두 얻을 수 있어요.","When one option solves two needs"],["I can go along with that.","그 의견에 따를 수 있어요.","When accepting a group decision"]],
      final:["What rule would make your next group order easier?","다음 단체 주문을 쉽게 만들 규칙 한 가지는 무엇인가요?","Next time, our rule should be..."]
    },
    {
      title:["Ping, Seen, No Reply","메시지는 읽었는데 답장이 없다"],category:"work",
      hook:["A teammate sends a short message: “Can we talk?” There is no context, and then they disappear for an hour. Another teammate sends ten separate messages for one simple request. Everyone uses the same work chat, but their habits are completely different.","팀원이 짧게 ‘잠깐 이야기할 수 있을까요?’라고 보냅니다. 설명은 없고 한 시간 동안 사라집니다. 다른 팀원은 간단한 요청 하나를 메시지 열 개로 나눠 보냅니다. 모두 같은 업무 메신저를 쓰지만 습관은 완전히 다릅니다."],
      goal:["Describe clear messaging habits and agree on respectful team rules.","명확한 메시지 습관을 설명하고 서로 배려하는 팀 규칙을 정합니다."],
      small:[["Which notification do you notice first?","어떤 알림을 가장 먼저 확인하나요?"],["Do you prefer one long message or several short ones?","긴 메시지 하나와 짧은 메시지 여러 개 중 무엇이 좋나요?"],["What does “quick question” mean to you?","‘간단한 질문’은 어느 정도라고 생각하나요?"]],
      quick:["vote","Message Manners Vote","메시지 매너 투표","Vote on whether each habit is acceptable or annoying. Compare one disagreement.","각 습관이 괜찮은지 불편한지 투표하고 의견이 다른 한 가지를 비교하세요.",["Sending only “Hi”","Using emojis with a manager","Replying with 👍 only","Messaging after work hours"]],
      easy:[["What helps you understand a work message quickly?","업무 메시지를 빨리 이해하는 데 무엇이 도움이 되나요?","A clear message includes...","What detail is often missing?"],["When is it okay to reply later?","언제 답장을 나중에 해도 괜찮을까요?","It is okay to wait when...","How should you show you saw it?"],["Which of your chat habits would you like to change?","자신의 메신저 습관 중 무엇을 바꾸고 싶나요?","I would like to stop/start...","What makes that difficult?"]],
      main:[["Does a fast reply always mean good communication?","빠른 답장이 항상 좋은 소통을 의미할까요?","A fast reply is useful when...","When has speed prevented confusion?","Could fast replies reduce the quality of decisions?"],["Should teams have rules for after-hours messages?","팀에 근무 시간 외 메시지 규칙이 있어야 할까요?","A reasonable rule would be...","What counts as a real emergency?","How can one rule fit people with different schedules?"],["How much tone should matter in text communication?","문자 소통에서 말투가 얼마나 중요할까요?","Tone matters because...","Which small word changes a message’s feeling?","Should readers assume good intentions when tone is unclear?"],["When should chat become a call or meeting?","언제 채팅을 통화나 회의로 바꿔야 할까요?","I would switch to a call when...","What warning sign tells you chat is failing?","How can teams avoid turning every issue into a meeting?"]],
      mid:["rewrite","Message Makeover","메시지 고쳐 쓰기","Rewrite two unclear messages with context, urgency, and a clear request. Read the best version aloud.","불분명한 메시지 두 개를 맥락, 긴급도, 요청이 드러나게 고쳐 쓰고 가장 좋은 문장을 읽으세요.",["Can we talk?","ASAP please","I need that thing","Why didn’t you reply?"]],
      phrases:[["Here’s the context in one sentence.","한 문장으로 상황을 설명드리면 이렇습니다.","Before making a request"],["No rush; tomorrow is fine.","급하지 않습니다. 내일까지 괜찮아요.","To lower unnecessary urgency"],["Would a five-minute call be clearer?","5분 통화가 더 명확할까요?","When chat becomes confusing"]],
      final:["Share one message habit that would make teamwork calmer.","팀의 소통을 더 편안하게 만들 메시지 습관 한 가지를 말해 보세요.","One helpful habit would be..."]
    },
    {
      title:["Plan Every Minute or Wander?","분 단위 계획인가, 즉흥 여행인가?"],category:"travel",
      hook:["Two friends are planning a three-day trip. One has a spreadsheet with every meal and train time. The other wants to book only a hotel and decide each morning. The tickets are cheaper today, but the weather forecast may change.","친구 두 명이 3일 여행을 계획합니다. 한 명은 식사와 기차 시간을 모두 적은 계획표가 있습니다. 다른 한 명은 숙소만 예약하고 매일 아침 결정하고 싶어 합니다. 오늘 표가 더 저렴하지만 날씨 예보는 바뀔 수 있습니다."],
      goal:["Balance preparation and flexibility to build a travel plan both people can enjoy.","준비와 유연성 사이의 균형을 찾아 모두가 즐길 여행 계획을 만듭니다."],
      small:[["What is the first thing you plan for a trip?","여행에서 가장 먼저 계획하는 것은 무엇인가요?"],["Window seat or aisle seat?","창가 자리와 통로 자리 중 어디가 좋나요?"],["What is worth booking early?","미리 예약할 가치가 있는 것은 무엇인가요?"]],
      quick:["tierList","Book It or Leave It","예약할까, 남겨 둘까","Put each item into Must book, Maybe, or Decide there.","각 항목을 반드시 예약, 상황에 따라, 현지에서 결정으로 나누세요.",["Hotel","Popular restaurant","Museum","Local transport","Free afternoon","Day trip"]],
      easy:[["How much free time do you want on a trip?","여행에서 자유 시간을 얼마나 원하나요?","I like to leave...","What do you do with that time?"],["What kind of plan makes travel less stressful?","어떤 계획이 여행 스트레스를 줄여 주나요?","I feel less stressed when...","Can too much planning add stress?"],["What would you let a travel partner choose?","여행 동행에게 무엇을 맡길 수 있나요?","They could choose...","What would you prefer to choose yourself?"]],
      main:[["What deserves a fixed plan and what should stay flexible?","무엇은 미리 정하고 무엇은 유연하게 남겨야 할까요?","I would definitely plan...","What happened when a plan changed unexpectedly?","Can flexibility sometimes be unfair to a travel partner?"],["How should travel partners handle different energy levels?","여행 동행의 체력 수준이 다르면 어떻게 해야 할까요?","A good solution would be...","Could the group split up for part of the day?","When does compromise reduce everyone’s enjoyment?"],["Is seeing more places always a better trip?","더 많은 곳을 보는 것이 항상 더 좋은 여행일까요?","A good trip is more about...","Which slow experience can be memorable?","How do social media checklists affect travel choices?"],["Who should make the final decision when partners disagree?","동행끼리 의견이 다를 때 누가 최종 결정해야 할까요?","The decision could be made by...","Would taking turns work?","What exception would require a different rule?"]],
      mid:["buildPlan","The 70% Itinerary","70% 여행 계획","Use seven cards to build a day that is 70% planned and 30% open. Explain where the flexibility is.","카드 일곱 장으로 70%는 계획하고 30%는 비워 둔 하루를 만들고 유연한 부분을 설명하세요.",["Breakfast","Travel time","Major sight","Lunch","Local walk","Rest","Dinner"]],
      phrases:[["Let’s keep that part flexible.","그 부분은 유연하게 남겨 두죠.","When a decision can wait"],["That’s the one thing I’d book ahead.","그건 제가 미리 예약할 한 가지예요.","When identifying a priority"],["We can adjust depending on the weather.","날씨에 따라 조정할 수 있어요.","When plans need a condition"]],
      final:["What is one non-negotiable and one flexible part of your ideal trip?","이상적인 여행에서 꼭 지킬 것 하나와 유연하게 둘 것 하나를 말해 보세요.","I’d definitely..., but I could be flexible about..."]
    },
    {
      title:["How Do You Pick a Café?","카페를 고르는 기준"],category:"lifestyle",
      hook:["You need a café for a two-hour conversation. The closest one is noisy, the quiet one has uncomfortable chairs, and the beautiful one has expensive drinks. A new place has no reviews yet. Your friend says, “You choose.”","두 시간 동안 대화할 카페가 필요합니다. 가장 가까운 곳은 시끄럽고, 조용한 곳은 의자가 불편하며, 예쁜 곳은 음료가 비쌉니다. 새 카페는 아직 리뷰가 없습니다. 친구가 ‘네가 골라’라고 합니다."],
      goal:["Compare everyday trade-offs and recommend the right café for a purpose.","일상의 선택 조건을 비교해 목적에 맞는 카페를 추천합니다."],
      small:[["What do you usually order at a café?","카페에서 보통 무엇을 주문하나요?"],["How long is a comfortable café visit?","카페에 얼마나 머무는 것이 편한가요?"],["Music, silence, or background noise?","음악, 조용함, 생활 소음 중 무엇이 좋나요?"]],
      quick:["rolePick","Pick the Place","장소 고르기","Choose a purpose card, then name the café feature that matters most for it.","목적 카드 하나를 고른 뒤 그 목적에 가장 중요한 카페 조건을 말하세요.",["First meeting","Working alone","Long chat","Quick takeaway"]],
      easy:[["What makes you stay longer in a café?","어떤 카페에서 더 오래 머물게 되나요?","I tend to stay longer when...","What makes you leave early?"],["Would you try a café with no reviews?","리뷰가 없는 카페를 가 볼 수 있나요?","I would try it if...","What clue would help you decide?"],["How much does atmosphere affect taste?","분위기가 맛에 얼마나 영향을 주나요?","The atmosphere makes...","Could great coffee overcome a bad space?"]],
      main:[["Should cafés design spaces for staying or for quick turnover?","카페는 오래 머무는 공간과 빠르게 회전하는 공간 중 무엇을 지향해야 할까요?","Cafés should focus on...","Which customers would benefit?","Can one space serve both groups fairly?"],["What makes a café price feel reasonable?","카페 가격이 합리적이라고 느끼게 하는 것은 무엇인가요?","The price feels fair when...","Does location change your answer?","Are customers paying for the drink or the time and space?"],["Do aesthetic cafés improve or distract from real connection?","예쁜 카페가 진짜 대화에 도움이 될까요, 방해가 될까요?","A beautiful space can...","When have surroundings changed a conversation?","Could a plain place create a more relaxed meeting?"],["What responsibility do customers have when using a café for hours?","카페를 여러 시간 이용할 때 손님에게 어떤 책임이 있을까요?","Customers should...","Is buying one drink enough?","How should the rule change when the café is empty?"]],
      mid:["design","Café Consultant","카페 컨설턴트","Pick four features for a new neighborhood café. You cannot choose all the premium options.","동네 새 카페를 위해 네 가지 조건을 고르세요. 모든 고급 조건을 고를 수는 없습니다.",["Quiet zone","Large tables","Low prices","Specialty coffee","Fast Wi-Fi","Late hours","Outdoor seats","Desserts"]],
      phrases:[["It has the right atmosphere for...","그곳은 …에 알맞은 분위기예요.","When matching a place to a purpose"],["The price is justified by...","… 때문에 그 가격이 납득돼요.","When explaining value"],["I’d trade a little comfort for...","…을 위해 편안함을 조금 포기할 수 있어요.","When making a trade-off"]],
      final:["Recommend one kind of café for this group and give one reason.","이 모임에 맞는 카페 유형을 한 가지 추천하고 이유를 말해 보세요.","I’d recommend a café that... because..."]
    },
    {
      title:["Subscribed, but Still Using It?","구독 중인데 아직도 쓰고 있나요?"],category:"shopping",
      hook:["Your bank statement shows five monthly subscriptions. You use two every week, one only sometimes, and you forgot the other two existed. Each service costs less than one restaurant meal, so none feels expensive alone. Together, they are a noticeable bill.","은행 명세서에 월간 구독이 다섯 개 보입니다. 두 개는 매주 쓰고, 하나는 가끔 쓰며, 나머지 두 개는 존재도 잊었습니다. 각각은 외식 한 번보다 저렴해 비싸게 느껴지지 않지만 모두 합치면 꽤 큰 금액입니다."],
      goal:["Evaluate convenience, habit, and value to decide which subscriptions deserve a place.","편리함, 습관, 가치를 평가해 어떤 구독을 유지할지 결정합니다."],
      small:[["Which kind of subscription is easiest to forget?","어떤 종류의 구독을 가장 쉽게 잊나요?"],["Do you prefer monthly or yearly payment?","월간 결제와 연간 결제 중 무엇이 좋나요?"],["What free service do you use often?","자주 사용하는 무료 서비스는 무엇인가요?"]],
      quick:["tierList","Keep, Pause, Cancel","유지, 일시정지, 해지","Sort the fictional subscriptions into Keep, Pause, or Cancel, then name one fact you still need.","가상의 구독을 유지, 일시정지, 해지로 분류하고 결정에 더 필요한 정보 한 가지를 말하세요.",["Music: daily","Video: twice a month","Cloud: important files","Fitness: unused","News: weekends"]],
      easy:[["What makes a subscription feel valuable?","구독이 가치 있다고 느끼는 기준은 무엇인가요?","It feels valuable when...","Does frequent use always mean good value?"],["Why are subscriptions easy to keep?","구독을 계속 유지하기 쉬운 이유는 무엇인가요?","People keep them because...","Which reminder would help?"],["What could replace one paid service?","유료 서비스 하나를 무엇으로 대신할 수 있나요?","Instead of paying, I could...","What convenience would you lose?"]],
      main:[["Is a cheap monthly price an honest way to show the real cost?","저렴한 월 가격이 실제 비용을 정직하게 보여 주는 방식일까요?","Monthly pricing feels...","Would a yearly total change decisions?","Should companies be required to show both totals equally?"],["Should services make cancellation as easy as sign-up?","구독 해지가 가입만큼 쉬워야 할까요?","Cancellation should...","What would a fair process look like?","Could very easy cancellation harm useful services?"],["Does access to more content improve choice or create overload?","더 많은 콘텐츠에 접근하면 선택이 좋아질까요, 부담이 커질까요?","More choice usually...","How do you decide what to use first?","When can fewer options create more value?"],["What is a fair way to judge a subscription you rarely use?","자주 쓰지 않는 구독의 가치를 공정하게 판단하는 방법은 무엇일까요?","I would judge it by...","Can peace of mind be valuable even without frequent use?","What exception should never be measured only by frequency?"]],
      mid:["budget","Subscription Audit","구독 점검","You have 30 points. Keep services within the budget and defend one surprising choice.","30포인트 안에서 서비스를 유지하고 의외의 선택 하나를 설명하세요.",["Music 7","Video 12","Cloud 8","Fitness 15","News 6","Learning 10"]],
      phrases:[["I’m not getting enough value out of it.","그 구독에서 충분한 가치를 얻지 못하고 있어요.","When considering cancellation"],["The convenience adds up over time.","그 편리함이 시간이 지나며 큰 가치가 돼요.","When defending recurring cost"],["I’d pause it rather than cancel it outright.","완전히 해지하기보다 일시정지하겠어요.","When choosing a middle option"]],
      final:["Choose one rule for reviewing your subscriptions.","구독을 점검할 규칙 한 가지를 정해 보세요.","My review rule would be..."]
    },
    {
      title:["A Recommendation for Everyone?","누구에게나 좋은 추천일까?"],category:"relationship",
      hook:["A friend recommends a series and says, “You’ll definitely love it.” You try two episodes and do not enjoy them. Later, another friend asks you for a recommendation, but you know your tastes are very different. A good recommendation needs more than naming your own favorite.","친구가 드라마를 추천하며 ‘너도 무조건 좋아할 거야’라고 말합니다. 두 편을 봤지만 재미가 없습니다. 나중에 취향이 아주 다른 친구가 추천을 부탁합니다. 좋은 추천은 내가 좋아하는 것을 말하는 것 이상이 필요합니다."],
      goal:["Ask useful questions, tailor a recommendation, and respond politely when tastes differ.","유용한 질문을 하고, 상대에게 맞춰 추천하며, 취향이 다를 때 정중하게 반응합니다."],
      small:[["What is something you often recommend?","자주 추천하는 것은 무엇인가요?"],["Do you trust friends or algorithms more?","친구와 알고리즘 중 누구의 추천을 더 믿나요?"],["How quickly do you know you dislike something?","무언가가 마음에 안 든다는 것을 얼마나 빨리 아나요?"]],
      quick:["rolePick","Match the Friend","친구에게 맞춰 추천하기","Pick a person and choose the best recommendation clue to ask about first.","인물을 하나 고르고 가장 먼저 물어볼 추천 기준을 고르세요.",["Busy friend","Adventurous friend","Budget-conscious friend","Comfort-seeking friend"]],
      easy:[["What information helps you recommend something?","무언가를 추천할 때 어떤 정보가 도움이 되나요?","First, I would ask...","Which answer changes your choice most?"],["How do you say a recommendation was not for you?","추천받은 것이 취향에 맞지 않았다고 어떻게 말하나요?","I’d say, “I can see why you liked it, but...”","Should you explain the reason?"],["When did a surprising recommendation work well?","의외의 추천이 잘 맞았던 때는 언제인가요?","I was surprised by...","What made you try it?"]],
      main:[["Is knowing the person more important than knowing the thing you recommend?","추천할 때 상대를 아는 것이 추천 대상을 아는 것보다 중요할까요?","A good recommendation depends more on...","What question reveals someone’s taste?","Can a stranger with expertise recommend better than a close friend?"],["Do algorithms broaden our taste or keep it narrow?","알고리즘은 취향을 넓힐까요, 좁게 가둘까요?","Algorithms tend to...","What unusual suggestion have you received?","Who should control how much variety appears?"],["Does rejecting a recommendation feel like rejecting the person?","추천을 거절하면 그 사람을 거절하는 것처럼 느껴질까요?","It can feel personal when...","How can both people keep it light?","Why do people connect favorites to identity?"],["What responsibility comes with a strong recommendation?","강하게 추천할 때 어떤 책임이 따를까요?","Before saying “you must try it,” I should...","Should recommenders mention drawbacks first?","When is enthusiasm more helpful than careful accuracy?"]],
      mid:["match","Recommendation Clinic","추천 상담소","One person describes a need without naming a product. Others ask two questions before recommending.","한 사람은 상품명을 말하지 않고 필요를 설명합니다. 다른 사람들은 질문 두 개를 한 뒤 추천합니다.",["A relaxing weekend activity","A useful gift","A quick meal","A short trip"]],
      phrases:[["It might suit you if you’re looking for...","…을 찾고 있다면 잘 맞을 수 있어요.","When tailoring a recommendation"],["It wasn’t quite my thing, but I can see the appeal.","제 취향은 아니었지만 매력은 이해해요.","When declining politely"],["What did you like about your last one?","지난번 것은 어떤 점이 좋았나요?","Before making a recommendation"]],
      final:["Give one recommendation and name exactly who it suits.","추천 하나를 하고 정확히 어떤 사람에게 맞는지 말해 보세요.","I’d recommend... to someone who..."]
    },
    {
      title:["Who Is Controlling the Screen?","화면을 통제하는 사람은 누구일까?"],category:"lifestyle",
      hook:["You pick up your phone to check the weather. Twenty minutes later, you are watching short videos and have forgotten the weather. The phone was useful, but the next action happened almost automatically. This small moment repeats throughout the day.","날씨를 확인하려고 스마트폰을 집어 듭니다. 20분 뒤 짧은 영상을 보고 있고 날씨는 잊었습니다. 스마트폰은 유용했지만 다음 행동은 거의 자동으로 일어났습니다. 이런 작은 순간이 하루 동안 반복됩니다."],
      goal:["Notice automatic phone habits and design one realistic boundary without blaming users.","무심코 반복하는 스마트폰 습관을 알아보고 사용자를 탓하지 않는 현실적인 경계 하나를 설계합니다."],
      small:[["Which phone tool saves you the most time?","스마트폰에서 시간을 가장 많이 아껴 주는 기능은 무엇인가요?"],["Which app do you open without thinking?","생각 없이 여는 앱은 무엇인가요?"],["Do you use your phone as an alarm clock?","스마트폰을 알람 시계로 쓰나요?"]],
      quick:["ranking","Keep or Remove","유지할까, 없앨까","Choose one feature to keep and one to remove for a week. Explain both choices.","일주일 동안 유지할 기능 하나와 없앨 기능 하나를 고르고 두 선택의 이유를 말하세요.",["Notifications","Infinite scroll","Read receipts","Autoplay","Screen-time report"]],
      easy:[["When is your phone most helpful?","스마트폰이 가장 도움이 되는 때는 언제인가요?","My phone is most helpful when...","What would be difficult without it?"],["What small phone habit interrupts you?","어떤 작은 스마트폰 습관이 집중을 방해하나요?","I get interrupted when...","Could one setting help?"],["Where would you like a phone-free moment?","어디에서 스마트폰 없는 시간을 갖고 싶나요?","I’d like to put my phone away during...","What might make that hard?"]],
      main:[["Are phone habits mainly personal choices or design results?","스마트폰 습관은 개인 선택일까요, 설계의 결과일까요?","They are influenced more by...","Which feature shapes behavior most?","How should responsibility be shared?"],["Should useful apps also protect our attention?","유용한 앱이 사용자의 주의력도 보호해야 할까요?","Apps should/shouldn’t...","What protection would still respect choice?","Could protection become unwanted control?"],["Is screen time a good measure of healthy use?","스크린 타임이 건강한 사용의 좋은 기준일까요?","Screen time is useful because...","What kind of use should count differently?","What better measure could include purpose and feeling?"],["What is a realistic boundary that people can maintain?","사람들이 지속할 수 있는 현실적인 경계는 무엇일까요?","A realistic boundary is...","What trigger would remind you?","When should breaking the rule be completely acceptable?"]],
      mid:["design","Attention Designer","주의력 디자이너","Redesign a phone home screen using only five items. Explain what you deliberately left out.","다섯 항목만 사용해 스마트폰 홈 화면을 다시 구성하고 일부러 뺀 것을 설명하세요.",["Calls","Messages","Camera","Maps","Music","Social media","Browser","Calendar","Weather"]],
      phrases:[["I opened it out of habit.","습관적으로 그 앱을 열었어요.","When an action was automatic"],["That feature pulls my attention away.","그 기능이 제 주의를 빼앗아요.","When describing distraction"],["I need a boundary I can actually maintain.","실제로 지킬 수 있는 경계가 필요해요.","When rejecting an extreme solution"]],
      final:["Choose one small phone boundary to try, or explain why you need none.","시도할 작은 스마트폰 경계 하나를 고르거나 필요 없는 이유를 말해 보세요.","One boundary I could try is..."]
    }
  ];

  function makeQuestion(parts) {
    return {questionEn:parts[0],questionKo:parts[1],starter:parts[2]||"",followUp:parts[3]||"",exampleFollowUp:parts[3]||"",deeperFollowUp:parts[4]||""};
  }
  function makeTopic(s, i) {
    const stamp = "2026-07-28T09:00:00.000Z";
    return {
      id:`talkflow-${dates[i]}-${i+1}`,date:dates[i],title:{en:s.title[0],ko:s.title[1]},category:s.category,
      hook:{en:s.hook[0],ko:s.hook[1]},goal:{en:s.goal[0],ko:s.goal[1]},
      smallTalk:s.small.map(makeQuestion),
      quickActivity:{type:s.quick[0],titleEn:s.quick[1],titleKo:s.quick[2],instructionEn:s.quick[3],instructionKo:s.quick[4],options:s.quick[5]},
      easyEntry:s.easy.map(makeQuestion),mainDiscussion:s.main.map(makeQuestion),
      midGame:{type:s.mid[0],titleEn:s.mid[1],titleKo:s.mid[2],instructionEn:s.mid[3],instructionKo:s.mid[4],options:s.mid[5]},
      usefulPhrases:s.phrases.map(p=>({en:p[0],ko:p[1],usage:p[2]})),
      finalRound:{questionEn:s.final[0],questionKo:s.final[1],starter:s.final[2]},
      leaderNotes:{estimatedMinutes:100,sensitiveWarning:"Avoid pressuring anyone to share private experiences.",whenConversationStops:["Can you give a simple example?","Which option feels closest to your view?","Would the answer change in a different situation?"],recommendedSkip:"Skip the final main question if the activity creates a strong discussion.",commonErrors:["Give each person thinking time before follow-ups.","Use the starter as support, not as a required script."]},
      quality:{status:"approved",score:100,issues:[]},hidden:false,createdAt:stamp,updatedAt:stamp
    };
  }
  window.TALKFLOW_SAMPLE_TOPICS = Object.fromEntries(specs.map((s,i)=>[dates[i],makeTopic(s,i)]));
})();
