import {createRequire} from "node:module";
import {createServer} from "node:http";
import {readFile,mkdir,writeFile} from "node:fs/promises";
import {existsSync} from "node:fs";
import {extname,join,normalize} from "node:path";
import {homedir} from "node:os";
import {fileURLToPath} from "node:url";

let playwright,PDFDocument;
try{playwright=createRequire(import.meta.url)("playwright");({PDFDocument}=createRequire(import.meta.url)("pdf-lib"))}catch{const runtime=join(homedir(),".cache","codex-runtimes","codex-primary-runtime","dependencies","node","node_modules");playwright=createRequire(join(runtime,"playwright","index.js"))("playwright");({PDFDocument}=createRequire(join(runtime,"pdf-lib","cjs","index.js"))("pdf-lib"))}
const {chromium}=playwright,root=fileURLToPath(new URL(".",import.meta.url)),evidence=join(root,"..",".omo","evidence","talkflow-simple"),pdfDir=join(root,".qa-pdf","simple");
await mkdir(evidence,{recursive:true});await mkdir(pdfDir,{recursive:true});
const mime={".html":"text/html; charset=utf-8",".css":"text/css",".js":"text/javascript",".json":"application/json"};
const server=createServer(async(req,res)=>{try{const pathname=new URL(req.url,"http://localhost").pathname,path=normalize(join(root,pathname==="/"?"index.html":pathname));if(!path.startsWith(normalize(root)))throw new Error("invalid path");res.setHeader("Content-Type",mime[extname(path)]||"application/octet-stream");res.end(await readFile(path))}catch{res.statusCode=404;res.end("Not found")}});await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
const specs=[
  ["2026-09-03","온라인 리뷰","Can We Trust Online Reviews?","온라인 리뷰를 믿어도 될까요?","story","Review Jury"],
  ["2026-09-07","친구 여행 계획","A Trip Everyone Can Enjoy","모두가 즐길 수 있는 여행","case","Build a Plan"],
  ["2026-09-10","업무 단체 채팅","A Better Work Group Chat","더 나은 업무 단체 채팅","trend","Advice Circle"],
  ["2026-09-14","배달 선택","Which Delivery Option Works Best?","어떤 배달 선택이 가장 좋을까요?","case","Rank and Negotiate"],
  ["2026-09-17","스마트폰 없는 하루","A Day Without a Smartphone","스마트폰 없는 하루","story","Best Option Challenge"]
];
const axes=["recentExperience","habit","comparison","criteria","opinion","decision"];
function fixture(topic){const spec=specs.find(item=>item[1]===topic.keyword),[date,keyword,titleEn,titleKo,style,activity]=spec;const plan={style,questionAxes:axes,activity,materialType:activity==="Review Jury"?"reviews":"conditions",groupResult:{en:"Our group decision and two reasons",ko:"그룹 결정과 이유 두 가지"}};const q=(en,ko,axis,example)=>({en,ko,axis,example});return{plan,content:{date,weekday:"목",category:{en:"LIFE",ko:"생활"},title:{en:titleEn,ko:titleKo},style,session1:{minutes:50,story:{heading:style==="case"?"THE SITUATION":"TODAY’S STORY",en:[`${keyword} became today's group question.`,"Three people had different experiences.","They compared practical details.","One shared decision was needed."],ko:[`${keyword}에 대해 세 사람의 경험이 달랐어요.`,"구체적인 정보를 비교하고 함께 결정해야 해요."]},easyTalk:[q("When did this last happen to you?","이런 일이 마지막으로 언제 있었어요?",axes[0],"It happened last week."),q("What is your usual habit?","평소 습관은 어때요?",axes[1],"I usually check the details."),q("Which option feels easier?","어떤 선택이 더 쉬워 보여요?",axes[2],"The first option feels easier.")],realTalk:[q("What detail matters most?","어떤 세부 정보가 가장 중요해요?",axes[3],"The time matters most."),q("What is your honest view?","솔직한 생각은 어때요?",axes[4],"I think balance is important."),q("What should the group decide?","그룹은 무엇을 결정해야 해요?",axes[5],"We should pick one option.")],expressions:[{en:"The key detail is…",ko:"핵심 정보는 …예요."},{en:"From my experience…",ko:"제 경험으로는 …"},{en:"I see it differently.",ko:"저는 다르게 생각해요."},{en:"Our group agrees that…",ko:"우리 그룹은 …에 동의해요."}]},session2:{minutes:40,reset:{en:"Look at the facts before making one group decision.",ko:"그룹 결정을 하기 전에 정보를 살펴봐요."},activity:{name:activity,instructionKo:"자료를 비교하고 각자의 근거를 말한 뒤 하나의 그룹 결정을 만들어요.",materials:[{en:"Option A: fast, simple, and expensive",ko:"선택 A: 빠르고 간단하지만 비싸요."},{en:"Option B: slower, flexible, and affordable",ko:"선택 B: 느리지만 유연하고 저렴해요."},{en:"Option C: balanced with one risk",ko:"선택 C: 균형이 있지만 위험 요소가 하나 있어요."}],stepsKo:["각자 가장 좋은 자료 하나와 이유를 말해요.","다른 사람의 근거에 질문을 하나 해요.","공통 기준 두 가지를 정해요.","그룹의 최종 결정을 기록해요."],phrases:["The strongest point is…","What is your reason?","I agree with that because…","Our final decision is…"],participationKo:"모든 사람이 선택, 질문, 반응을 각각 한 번씩 말해요."},groupResult:{en:"Our final decision is ___ because ___ and ___.",ko:"최종 결정과 이유 두 가지를 적어요.",type:"decision"},finalQuestion:{en:"What will you do differently next time?",ko:"다음에는 무엇을 다르게 할 거예요?"}},leader:{story:"학습자의 실제 경험 하나를 먼저 받아요.",easyTalk:"짧은 답 뒤에 한 가지 세부 정보를 요청해요.",realTalk:"서로 다른 기준을 비교하게 해요.",activity:"전원이 선택, 질문, 반응을 말했는지 확인해요.",final:"다음 행동이 포함된 답으로 마무리해요.",emergency:["Could you say a little more?","Who has a different view?","What is your reason?","Let’s make one group answer."],timeCutKo:"시간이 부족하면 질문 하나를 줄이고 그룹 결과는 반드시 남겨요."}}}}
const baseFixture=fixture;fixture=topic=>{const value=baseFixture(topic);value.content.session1.story.ko.push("서로의 기준을 듣고 공통점을 찾기로 했어요.");return value};
const systemChrome="C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",browser=await chromium.launch({headless:true,...(existsSync(systemChrome)?{executablePath:systemChrome}:{})}),checks=[];const check=(name,pass,detail="")=>{checks.push({name,pass:Boolean(pass),detail});if(!pass)throw new Error(`${name}: ${detail}`)};
try{const context=await browser.newContext({viewport:{width:1280,height:900}});await context.addInitScript(()=>localStorage.setItem("tb_talkflow_settings_v1",JSON.stringify({apiKey:"qa-intercept-key"})));const page=await context.newPage(),errors=[];page.on("pageerror",error=>errors.push(error.message));const calls=[];
await page.route("https://api.anthropic.com/v1/messages",async route=>{const body=route.request().postDataJSON(),data=JSON.parse(body.messages[0].content),tool=body.tools[0].name,payload=fixture(data.topic);calls.push({tool,keyword:data.topic.keyword});await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({content:[{type:"tool_use",name:tool,input:tool==="submit_simple_topic_plan"?payload.plan:payload.content}]})})});
await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:"networkidle"});const before=await page.evaluate(()=>localStorage.getItem("tb_talkflow_v1")),generated=[];for(const [date,keyword] of specs)generated.push(await page.evaluate(input=>TalkFlow.generateForTest(input),{date,keyword,mood:"경험 중심"}));
check("five topics use the real two-stage path",generated.length===5&&calls.filter(call=>call.tool==="submit_simple_topic_plan").length===5&&calls.filter(call=>call.tool==="submit_simple_content").length===5);check("all topics pass Simple validation",await page.evaluate(items=>items.every(item=>TalkFlow.generation.evaluate(item).ready),generated));check("monthly styles are mixed",new Set(generated.map(item=>item.style)).size===3);check("online review uses only Review Jury",generated[0].session2.activity.name==="Review Jury");check("test generation leaves operational storage untouched",await page.evaluate(()=>localStorage.getItem("tb_talkflow_v1"))===before);const malformed=structuredClone(generated[0]);malformed.session2.activity.phrases=[];delete malformed.leader.story;check("malformed imported content fails closed",await page.evaluate(item=>!TalkFlow.generation.evaluate(item).ready,malformed));check("Simple lifecycle is not marked legacy",await page.evaluate(item=>TalkFlow.lifecycle(item).key!=="invalid",generated[0]));check("public viewer supports Simple topics",await page.evaluate(item=>{const html=TalkFlow.viewerHtml({[item.date]:item});return html.includes("SIMPLE CONVERSATION")&&html.includes("session1.easyTalk")},generated[0]));
for(let index=0;index<generated.length;index++){const topic=generated[index];topic.quality={status:"approved",score:100,issues:[]};topic.operatorStatus.reviewStatus="approved";await page.evaluate(item=>localStorage.setItem("tb_talkflow_v1",JSON.stringify({[item.date]:item})),topic);await page.goto(`http://127.0.0.1:${server.address().port}/?date=${topic.date}&view=print`,{waitUntil:"networkidle"});check(`${topic.generationRequest.keyword}: two pages`,await page.locator(".simple-handout .a4-page").count()===2);check(`${topic.generationRequest.keyword}: page sections`,await page.locator(".simple-page-1>.simple-section").count()===4&&await page.locator(".simple-page-2>.simple-section").count()===4);const metric=await page.locator(".simple-handout .a4-page").evaluateAll(nodes=>nodes.map(node=>({v:node.scrollHeight-node.clientHeight,h:node.scrollWidth-node.clientWidth})));check(`${topic.generationRequest.keyword}: no overflow`,metric.every(item=>item.v<=1&&item.h<=1),JSON.stringify(metric));const print=await page.evaluate(item=>TalkFlow.evaluateRenderedPrint(item),topic);check(`${topic.generationRequest.keyword}: print floors`,print.status==="ready",JSON.stringify(print));const pdf=await page.pdf({path:join(pdfDir,`student-${index+1}.pdf`),format:"A4",printBackground:true,preferCSSPageSize:true,margin:{top:"0",right:"0",bottom:"0",left:"0"}});check(`${topic.generationRequest.keyword}: PDF two pages`,(await PDFDocument.load(pdf)).getPageCount()===2);await page.addStyleTag({content:".topbar,.daily-nav,.leader-toolbar,.print-toolbar{display:none!important}"});for(let pageIndex=0;pageIndex<2;pageIndex++)await page.locator(".simple-handout .a4-page").nth(pageIndex).screenshot({path:join(evidence,`student-${index+1}-page-${pageIndex+1}.png`)})}
for(const field of ["phrases","leader","reset"]){const mutant=structuredClone(generated[0]);if(field==="phrases")mutant.session2.activity.phrases=[];if(field==="leader")delete mutant.leader.story;if(field==="reset")delete mutant.session2.reset;check(`fail-closed ${field}`,await page.evaluate(item=>!TalkFlow.generation.evaluate(item).ready,mutant))}const viewer=await page.evaluate(item=>TalkFlow.viewerHtml({[item.date]:item}),generated[0]),viewerPage=await context.newPage();await viewerPage.setContent(viewer,{waitUntil:"load"});check("public viewer executes Simple topic",await viewerPage.getByRole("heading",{name:"Can We Trust Online Reviews?"}).count()===1&&await viewerPage.getByText("TODAY’S ACTIVITY",{exact:false}).count()>=1);await viewerPage.close();const leader=generated[0];await page.evaluate(item=>localStorage.setItem("tb_talkflow_v1",JSON.stringify({[item.date]:item})),leader);await page.goto(`http://127.0.0.1:${server.address().port}/?date=${leader.date}&view=student`,{waitUntil:"networkidle"});check("normal Student view routes Simple renderer",await page.locator("#student-view .simple-handout").count()===1);await page.goto(`http://127.0.0.1:${server.address().port}/?date=${leader.date}&view=leader`,{waitUntil:"networkidle"});check("normal Leader view routes Simple renderer",await page.locator("#leader-view .simple-leader-handout").count()===1);await page.evaluate(item=>{document.body.innerHTML=TalkFlow.renderForTest(item,true)},leader);check("leader renderer uses Simple design",await page.locator(".simple-leader-handout .simple-leader-note").count()>=4);const leaderPdf=await page.pdf({path:join(pdfDir,"leader-online-review.pdf"),format:"A4",printBackground:true,preferCSSPageSize:true,margin:{top:"0",right:"0",bottom:"0",left:"0"}});check("leader PDF two pages",(await PDFDocument.load(leaderPdf)).getPageCount()===2);await page.locator(".simple-leader-handout .a4-page").first().screenshot({path:join(evidence,"leader.png")});await page.evaluate(item=>localStorage.setItem("tb_talkflow_v1",JSON.stringify({[item.date]:item})),leader);
for(const width of [375,768,1280]){await page.setViewportSize({width,height:900});await page.goto(`http://127.0.0.1:${server.address().port}/?date=${leader.date}&view=admin`,{waitUntil:"networkidle"});check(`${width}px no horizontal overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1));await page.screenshot({path:join(evidence,`admin-${width}.png`),fullPage:true})}check("console error zero",errors.length===0,errors.join(" | "));const report={pass:true,checks:checks.length,generatedAt:new Date().toISOString(),pdfDir,evidence,results:checks};await writeFile(join(evidence,"report.json"),JSON.stringify(report,null,2));console.log(`simple-qa: PASS (${checks.length} checks)`)}finally{await browser.close();server.close()}
