import {createRequire} from "node:module";
import {createServer} from "node:http";
import {readFile,mkdir,writeFile} from "node:fs/promises";
import {existsSync} from "node:fs";
import {extname,join,normalize} from "node:path";
import {homedir} from "node:os";
import {fileURLToPath} from "node:url";

let playwright,PDFDocument;
try{playwright=createRequire(import.meta.url)("playwright");({PDFDocument}=createRequire(import.meta.url)("pdf-lib"))}catch{const runtime=join(homedir(),".cache","codex-runtimes","codex-primary-runtime","dependencies","node","node_modules");playwright=createRequire(join(runtime,"playwright","index.js"))("playwright");({PDFDocument}=createRequire(join(runtime,"pdf-lib","cjs","index.js"))("pdf-lib"))}
const {chromium}=playwright,root=fileURLToPath(new URL(".",import.meta.url)),evidence=join(root,"..",".omo","evidence","talkflow-simple"),pdfDir=join(root,".qa-pdf","simple");
await mkdir(evidence,{recursive:true});await mkdir(pdfDir,{recursive:true});
const mime={".html":"text/html; charset=utf-8",".css":"text/css",".js":"text/javascript",".json":"application/json"};
const server=createServer(async(req,res)=>{try{const pathname=new URL(req.url,"http://localhost").pathname,path=normalize(join(root,pathname==="/"?"index.html":pathname));if(!path.startsWith(normalize(root)))throw new Error("invalid path");res.setHeader("Content-Type",mime[extname(path)]||"application/octet-stream");res.end(await readFile(path))}catch{res.statusCode=404;res.end("Not found")}});await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
const specs=[
  ["2026-09-03","온라인 리뷰","Can We Trust Online Reviews?","온라인 리뷰를 믿어도 될까요?","story","Review Jury"],
  ["2026-09-07","친구 여행 계획","A Trip Everyone Can Enjoy","모두가 즐길 수 있는 여행","case","Build a Plan"],
  ["2026-09-10","업무 단체 채팅","A Better Work Group Chat","더 나은 업무 단체 채팅","trend","Advice Circle"],
  ["2026-09-14","배달 선택","Which Delivery Option Works Best?","어떤 배달 선택이 가장 좋을까요?","case","Rank and Negotiate"],
  ["2026-09-17","스마트폰 없는 하루","A Day Without a Smartphone","스마트폰 없는 하루","story","Best Option Challenge"]
  ,["2026-09-21","카페에서 자리 맡기","Saving a Seat at a Busy Café","붐비는 카페에서 자리 맡기","case","Mini Role Play"]
  ,["2026-09-24","약속 시간과 지각","How Late Is Too Late?","약속 시간과 지각","trend","Advice Circle"]
  ,["2026-09-28","구독 서비스 정리","Which Subscription Should Go?","어떤 구독을 정리할까요?","case","Choose and Defend"]
];
const axes=["recentExperience","dailyHabit","quickChoice","personalStory","evaluationCriteria","tradeoff"];
function fixture(topic){const spec=specs.find(item=>item[1]===topic.keyword),[date,keyword,titleEn,titleKo,style,activity]=spec;const plan={style,questionAxes:axes,activity,materialType:activity==="Review Jury"?"reviews":"conditions",groupResult:{en:"Our group decision and two reasons",ko:"그룹 결정과 이유 두 가지"}};const q=(en,ko,axis,example)=>({en,ko,axis,example});return{plan,content:{date,weekday:"목",category:{en:"LIFE",ko:"생활"},title:{en:titleEn,ko:titleKo},style,session1:{minutes:50,story:{heading:style==="case"?"THE SITUATION":"TODAY’S STORY",en:[`${keyword} became today's group question.`,"Three people had different experiences.","They compared practical details.","One shared decision was needed."],ko:[`${keyword}에 대해 세 사람의 경험이 달랐어요.`,"구체적인 정보를 비교하고 함께 결정해야 해요."]},easyTalk:[q("When did this last happen to you?","이런 일이 마지막으로 언제 있었어요?",axes[0],"It happened last week."),q("What is your usual habit?","평소 습관은 어때요?",axes[1],"I usually check the details."),q("Which option feels easier?","어떤 선택이 더 쉬워 보여요?",axes[2],"The first option feels easier.")],realTalk:[q("What detail matters most?","어떤 세부 정보가 가장 중요해요?",axes[3],"The time matters most."),q("What is your honest view?","솔직한 생각은 어때요?",axes[4],"I think balance is important."),q("What should the group decide?","그룹은 무엇을 결정해야 해요?",axes[5],"We should pick one option.")],expressions:[{en:"The key detail is…",ko:"핵심 정보는 …예요."},{en:"From my experience…",ko:"제 경험으로는 …"},{en:"I see it differently.",ko:"저는 다르게 생각해요."},{en:"Our group agrees that…",ko:"우리 그룹은 …에 동의해요."}]},session2:{minutes:40,reset:{en:"Look at the facts before making one group decision.",ko:"그룹 결정을 하기 전에 정보를 살펴봐요."},activity:{name:activity,instructionKo:"자료를 비교하고 각자의 근거를 말한 뒤 하나의 그룹 결정을 만들어요.",materials:[{en:"Option A: fast, simple, and expensive",ko:"선택 A: 빠르고 간단하지만 비싸요."},{en:"Option B: slower, flexible, and affordable",ko:"선택 B: 느리지만 유연하고 저렴해요."},{en:"Option C: balanced with one risk",ko:"선택 C: 균형이 있지만 위험 요소가 하나 있어요."}],stepsKo:["각자 가장 좋은 자료 하나와 이유를 말해요.","다른 사람의 근거에 질문을 하나 해요.","공통 기준 두 가지를 정해요.","그룹의 최종 결정을 기록해요."],phrases:["The strongest point is…","What is your reason?","I agree with that because…","Our final decision is…"],participationKo:"모든 사람이 선택, 질문, 반응을 각각 한 번씩 말해요."},groupResult:{en:"Our final decision is ___ because ___ and ___.",ko:"최종 결정과 이유 두 가지를 적어요.",type:"decision"},finalQuestion:{en:"What will you do differently next time?",ko:"다음에는 무엇을 다르게 할 거예요?"}},leader:{story:"학습자의 실제 경험 하나를 먼저 받아요.",easyTalk:"짧은 답 뒤에 한 가지 세부 정보를 요청해요.",realTalk:"서로 다른 기준을 비교하게 해요.",activity:"전원이 선택, 질문, 반응을 말했는지 확인해요.",final:"다음 행동이 포함된 답으로 마무리해요.",emergency:["Could you say a little more?","Who has a different view?","What is your reason?","Let’s make one group answer."],timeCutKo:"시간이 부족하면 질문 하나를 줄이고 그룹 결과는 반드시 남겨요."}}}}
const baseFixture=fixture;fixture=topic=>{const value=baseFixture(topic),story=value.content.session1.story,activity=value.content.session2.activity;story.id=`story-${topic.date}`;story.en=[`${topic.keyword} became a real decision at 7:30 p.m.`,"Mina and two friends expected the easiest option to work for everyone.","However, one detail was different from what they had expected, and each person cared about a different result.","They had only 25 minutes and a budget of 30,000 won, so waiting or paying more could both cause a problem.","No option was clearly best for time, cost, and the relationship.","What should the group do next?"];story.ko=[`${topic.keyword} 문제를 두고 미나와 친구 두 명이 저녁 7시 30분에 결정을 해야 했어요.`,"예상과 다른 조건이 생겼고 세 사람은 시간, 비용, 편리함을 서로 다르게 중요하게 봤어요.","남은 시간은 25분이고 예산은 3만 원이라 어느 선택도 완벽하지 않았어요.","그룹은 다음에 무엇을 할지 정해야 해요."];[...value.content.session1.easyTalk,...value.content.session1.realTalk].forEach((question,index)=>{question.starter=["The last time was…","I usually…","I would pick…","One example is…","The key point is…","I would accept…"][index]});value.content.session1.expressions.forEach((item,index)=>item.useIn=[["story","activity"],["realTalk"],["realTalk","activity"],["activity"]][index]);activity.sourceRef=story.id;activity.disagreementKo="시간, 비용, 편리함의 우선순위가 달라 서로 다른 선택이 가능해요.";activity.listeningKo="다른 사람의 근거를 요약한 뒤 자신의 의견을 말해요.";activity.estimatedMinutes=20;value.content.leader.easyTalkFollowups=["When exactly?","Is that your usual choice?","What condition would change it?"];value.content.leader.realTalkFollowups=["Can you give us an example?","Why is that your main criterion?","Does anyone disagree?"];value.content.leader.activitySupport={demoKo:"자료 하나를 골라 이유 한 문장으로 시범을 보여요.",quietKo:"조용한 참가자에게 첫 선택을 먼저 물어요.",longKo:"핵심 기준 하나로 정리해 달라고 요청해요.",timeCutKo:"비교 단계를 하나 줄이고 최종 결과는 남겨요.",fastAgreementKo:"예산이 20% 줄었다는 추가 조건을 제시해요."};return value};
const enrichedFixture=fixture,questionSets=[
  ["What was the last thing you bought after reading reviews?","What do you check first in a review?","Would you trust 4.9 stars from only three people?","When did a product differ from its reviews?","What detail makes a review believable?","Would you pay 6,000 won to return a disappointing jacket?"],
  ["What was your most recent trip with friends?","How do you usually plan a group trip?","Would you pick a cheap room 40 minutes from downtown?","When did friends want different things on a trip?","Which matters more, time or comfort?","How should four friends use a 300,000-won budget?"],
  ["What was the last useful message in your work chat?","When do you normally reply to a group message?","Would you mute a busy chat during a deadline?","When did one message cause confusion at work?","What makes a group message clear?","Should a team ban messages after 8 p.m.?"],
  ["What was the last meal you ordered for a group?","What do you usually compare before ordering?","Would you reorder great food after a 90-minute wait?","When did a delivery choice disappoint your group?","Which matters more, speed or taste?","Would you pay 5,000 won more for reliable delivery?"],
  ["When did you last leave your phone at home?","What do you normally use your phone for first?","Would you spend one workday with only calls?","When did your phone distract you at a bad time?","Which phone function is hardest to lose?","Should friends put phones away for a two-hour dinner?"],
  ["When did you last look for a café seat?","How do you usually save a seat at a café?","Would you leave a laptop on a table for ten minutes?","When did seat-saving feel unfair?","What makes saving a seat acceptable?","Should a crowded café limit empty seats to 15 minutes?"],
  ["When was someone recently late to meet you?","How early do you normally arrive?","Would you wait 30 minutes without a message?","When did being late change a plan?","Which matters more, the reason or the warning?","What should friends do after a third late arrival?"],
  ["What subscription did you use most recently?","How often do you check monthly payments?","Would you keep a 12,000-won service used twice a month?","When did a free trial become a paid subscription?","What makes a subscription worth keeping?","Which two services should a family keep under 30,000 won?"]
],expressionSets=[
  ["It looked different in person.","I relied on the photo reviews.","That rating does not convince me.","What detail changed your mind?"],
  ["That fits our travel budget.","We ran out of time last trip.","Comfort matters more to me.","Which condition can we change?"],
  ["That message needs more context.","I missed the deadline update.","I see the urgency differently.","Who needs this information now?"],
  ["The wait changed my opinion.","I ordered it for our group.","Taste is not the only factor.","Would the fee change your choice?"],
  ["I reached for my phone automatically.","I managed without that app.","That rule feels too strict.","When would you need an exception?"],
  ["That seat is not being used.","I left my bag for five minutes.","I understand both sides.","How long feels reasonable?"],
  ["I should have sent a message.","The delay changed our plan.","The reason matters to me.","Would an apology be enough?"],
  ["I forgot the trial ended.","I barely use this service.","That benefit is worth the fee.","What would make you cancel it?"]
];fixture=topic=>{const value=enrichedFixture(topic),index=specs.findIndex(item=>item[1]===topic.keyword),questions=[...value.content.session1.easyTalk,...value.content.session1.realTalk];questions.forEach((question,questionIndex)=>{question.en=questionSets[index][questionIndex];question.ko=["최근의 구체적인 경험을 말해요.","평소 습관을 바로 말해요.","조건을 보고 빠르게 골라요.","주변의 실제 사례를 말해요.","판단할 때 중요한 기준을 말해요.","조건 사이에서 해결책을 정해요."][questionIndex]});value.content.session1.expressions.forEach((expression,expressionIndex)=>expression.en=expressionSets[index][expressionIndex]);value.content.session1.story.en[0]=`${["Jina","Minho","Sora","Daniel","Yuna","Alex","Mina","Joon"][index]} faced a real ${topic.keyword} decision at ${["8:10 p.m.","9:00 a.m.","7:45 p.m.","6:20 p.m.","8:30 a.m.","2:15 p.m.","6:40 p.m.","10:05 p.m."][index]}.`;return value};
const scenarioFixture=fixture,scenarios=[
  {en:["Jina ordered a jacket after seeing 4.8 stars and 42 photo reviews.","She expected a thick navy jacket, but the delivered color was gray and the material felt thin.","The shop accepts returns within three days, but shipping costs 6,000 won.","Her friend says the jacket still looks fine, while Jina worries it will not last through winter.","Keeping it saves time; returning it protects her budget for a better coat.","Should she keep it or send it back?"],ko:["지나는 사진 후기 42개와 별점 4.8을 보고 남색 재킷을 주문했어요.","도착한 옷은 회색에 가깝고 생각보다 얇았어요.","3일 안에 반품할 수 있지만 배송비가 6천 원이고 친구는 그냥 입어도 괜찮다고 해요.","지나는 시간을 아낄지 더 나은 옷을 위해 반품할지 결정해야 해요."],result:"Our final rating is ___, and we would buy / not buy it.",final:"Which review detail will you check before your next purchase?"},
  {en:["Minho and three friends found a guesthouse for 280,000 won near the beach.","They expected a quiet weekend, but a new review says construction starts at 7 a.m.","A quieter hotel costs 90,000 won more and is 40 minutes from the beach.","Two friends value sleep, while the others want to stay close to the water.","They must book before noon because both places have one room left.","Which place should the group choose?"],ko:["민호와 친구 세 명은 해변 근처 28만 원짜리 숙소를 찾았어요.","조용할 거라 기대했지만 최근 후기에 오전 7시부터 공사가 시작된다고 적혀 있었어요.","조용한 호텔은 9만 원 더 비싸고 해변에서 40분 거리예요.","정오 전에 둘 중 한 곳을 예약해야 해요."],result:"Our group books ___ with a total budget of ___.",final:"Which travel condition became most important today?"},
  {en:["Sora's team chat received 68 messages between 7 and 9 p.m. before a Friday deadline.","She expected only urgent updates, but most messages repeated information already in the shared file.","One quiet teammate missed a changed meeting time hidden in the thread.","Turning off messages protects focus, while keeping them on may prevent another missed update.","The manager wants one rule that works for both urgent and routine messages.","What rule should the team adopt?"],ko:["소라의 팀 채팅방에는 금요일 마감 전 저녁 7시부터 9시까지 메시지 68개가 올라왔어요.","긴급 내용만 올 거라 생각했지만 대부분 공유 파일의 내용을 반복했어요.","한 팀원은 대화 속에 묻힌 회의 시간 변경을 놓쳤어요.","팀은 집중과 긴급 연락을 모두 지킬 규칙 하나를 정해야 해요."],result:"Our team chat rule is ___, with one exception for ___.",final:"What message rule would improve your next group chat?"},
  {en:["Daniel ordered dinner for four people from a restaurant rated 4.7 stars.","The app predicted 35 minutes, but after 70 minutes the driver had not arrived.","Canceling now gives a full refund, while a new order would cost 5,000 won more and take 30 minutes.","Two friends want to wait for the favorite meal; the others are hungry and want certainty.","The restaurant offers a free drink if they keep the order.","Should the group wait, cancel, or reorder elsewhere?"],ko:["다니엘은 별점 4.7인 식당에서 네 명의 저녁을 주문했어요.","35분 예정이었지만 70분이 지나도 음식이 오지 않았어요.","지금 취소하면 전액 환불이고 다른 곳은 5천 원 더 들지만 30분 안에 와요.","친구들은 기다릴지 취소할지 의견이 달라요."],result:"Our delivery choice is ___ because time / taste / price matters most.",final:"What delivery condition would change your decision next time?"},
  {en:["Yuna agreed to spend a Saturday without smartphone apps from 9 a.m. to 9 p.m.","She expected a relaxing day, but her bus ticket, café coupon, and friend's address were all on her phone.","Using calls is allowed, while opening any app ends the challenge.","Her friend wants to keep the rule; Yuna worries they will miss a 3 p.m. reservation.","They can print the ticket now or change the challenge before leaving.","What should they allow and still call it a phone-free day?"],ko:["유나는 오전 9시부터 오후 9시까지 스마트폰 앱 없이 지내기로 했어요.","쉬울 거라 생각했지만 버스표, 카페 쿠폰, 친구 주소가 모두 휴대폰에 있었어요.","전화는 가능하지만 앱을 열면 도전이 끝나요.","오후 3시 예약을 지키면서 어떤 예외를 둘지 정해야 해요."],result:"Our phone-free rule allows ___ but blocks ___.",final:"What would you prepare before your own phone-free day?"},
  {en:["Alex entered a crowded café at 2:15 p.m. and saw one empty table with a laptop on it.","The staff expected the owner back quickly, but no one returned for 18 minutes.","A sign asks customers not to leave seats empty for more than 15 minutes.","Alex needs a table for a 30-minute video call, while another customer says moving the laptop is rude.","The staff can store the laptop safely at the counter.","What should Alex and the staff do?"],ko:["알렉스는 오후 2시 15분 붐비는 카페에서 노트북만 놓인 빈자리를 봤어요.","주인이 곧 올 줄 알았지만 18분 동안 돌아오지 않았고 안내문에는 15분 이상 자리를 비우지 말라고 적혀 있었어요.","알렉스는 30분 화상 통화가 필요하지만 다른 손님은 노트북을 옮기면 무례하다고 해요.","직원과 알렉스는 어떻게 해야 할지 정해야 해요."],result:"Our café seat rule is ___ after ___ minutes.",final:"What is the fairest way to save a seat in a busy place?"},
  {en:["Mina planned to meet a friend at 6:40 p.m. before a 7:30 movie.","Her friend expected to arrive on time but sent a message at 6:45 saying the train was delayed.","The next message came 20 minutes later, and the friend was still three stops away.","Waiting keeps the promise, while entering alone avoids losing two 15,000-won tickets.","This is the friend's third late arrival this month.","Should Mina wait, enter, or change future plans?"],ko:["미나는 오후 6시 40분에 친구를 만나 7시 30분 영화를 보기로 했어요.","친구는 제시간에 올 줄 알았지만 6시 45분에 지하철이 늦는다고 연락했어요.","20분 뒤에도 세 정거장이 남았고 표 두 장은 각각 1만 5천 원이에요.","이번 달 세 번째 지각이라 미나는 기다릴지 먼저 들어갈지 정해야 해요."],result:"Our late-arrival agreement is ___ after ___ minutes.",final:"What would you communicate differently before the next meeting?"},
  {en:["Joon checked his bank app at 10:05 p.m. and found six subscriptions costing 54,000 won each month.","He expected to use all of them, but two services had not been opened for 45 days.","One unused service stores family photos, while another includes music his sister uses every morning.","Canceling both saves money but may remove shared files or upset a family member.","The family wants to keep the total under 30,000 won by midnight.","Which services should they keep or cancel?"],ko:["준은 밤 10시 5분 은행 앱에서 매달 5만 4천 원이 나가는 구독 여섯 개를 발견했어요.","모두 쓸 줄 알았지만 두 서비스는 45일 동안 열지 않았어요.","하나는 가족 사진을 보관하고 다른 하나는 동생이 매일 듣는 음악을 제공해요.","자정까지 월 구독료를 3만 원 아래로 줄여야 해요."],result:"We keep ___ and cancel ___ for a monthly total of ___.",final:"What rule will you use for your next subscription review?"}
];const resultKo=["최종 별점과 구매 여부를 정해요.","선택한 숙소와 총예산을 적어요.","팀 채팅 규칙과 예외 하나를 정해요.","배달 선택과 가장 중요한 기준을 적어요.","허용할 기능과 막을 기능을 정해요.","몇 분 뒤 자리를 비운 것으로 볼지 규칙을 정해요.","몇 분 뒤 적용할 지각 약속을 정해요.","유지·해지할 서비스와 월 합계를 적어요."],finalKo=["다음 구매 전에 어떤 리뷰 정보를 확인할 거예요?","오늘 가장 중요해진 여행 조건은 무엇이었어요?","다음 단체 채팅을 개선할 규칙은 무엇이에요?","다음에는 어떤 배달 조건이 선택을 바꿀까요?","스마트폰 없는 하루 전에 무엇을 준비할 거예요?","붐비는 장소에서 자리를 맡는 가장 공정한 방법은 무엇일까요?","다음 약속 전에는 무엇을 다르게 전달할 거예요?","다음 구독 점검에는 어떤 기준을 사용할 거예요?"];fixture=topic=>{const value=scenarioFixture(topic),index=specs.findIndex(item=>item[1]===topic.keyword),scenario=scenarios[index];value.content.session1.story.en=scenario.en;value.content.session1.story.ko=scenario.ko;value.content.session2.activity.materials=scenario.en.slice(0,3).map((en,materialIndex)=>({en,ko:scenario.ko[Math.min(materialIndex,scenario.ko.length-1)]}));value.content.session2.groupResult.en=scenario.result;value.content.session2.groupResult.ko=resultKo[index];value.content.session2.finalQuestion.en=scenario.final;value.content.session2.finalQuestion.ko=finalKo[index];return value};
const answerFixture=fixture;fixture=topic=>{const value=answerFixture(topic),questions=[...value.content.session1.easyTalk,...value.content.session1.realTalk];questions.forEach((question,index)=>{question.reasonPrompt="My main reason is…";question.longAnswerPrompt=index<3?"For example, last time…":"One exception would be…"});value.content.session2.activity.phrases=value.content.session1.expressions.map(expression=>expression.en);value.content.session1.expressions.forEach(expression=>{if(!expression.useIn.includes("activity"))expression.useIn.push("activity")});return value};
const systemChrome="C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",browser=await chromium.launch({headless:true,...(existsSync(systemChrome)?{executablePath:systemChrome}:{})}),checks=[];const check=(name,pass,detail="")=>{checks.push({name,pass:Boolean(pass),detail});if(!pass)throw new Error(`${name}: ${detail}`)};
try{const context=await browser.newContext({viewport:{width:1280,height:900}});await context.addInitScript(()=>localStorage.setItem("tb_talkflow_settings_v1",JSON.stringify({apiKey:"qa-intercept-key"})));const page=await context.newPage(),errors=[];page.on("pageerror",error=>errors.push(error.message));const calls=[];
await page.route("https://api.anthropic.com/v1/messages",async route=>{const body=route.request().postDataJSON(),data=JSON.parse(body.messages[0].content),tool=body.tools[0].name,payload=fixture(data.topic);calls.push({tool,keyword:data.topic.keyword});await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({content:[{type:"tool_use",name:tool,input:tool==="submit_simple_topic_plan"?payload.plan:payload.content}]})})});
await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:"networkidle"});const before=await page.evaluate(()=>localStorage.getItem("tb_talkflow_v1")),generated=[];for(const [date,keyword] of specs)generated.push(await page.evaluate(input=>TalkFlow.generateForTest(input),{date,keyword,mood:"경험 중심"}));
check("eight topics use the real two-stage path",generated.length===8&&calls.filter(call=>call.tool==="submit_simple_topic_plan").length===8&&calls.filter(call=>call.tool==="submit_simple_content").length===8);check("all topics pass Simple validation",await page.evaluate(items=>items.every(item=>TalkFlow.generation.evaluate(item).ready),generated));check("monthly styles are mixed",new Set(generated.map(item=>item.style)).size===3);check("online review uses only Review Jury",generated[0].session2.activity.name==="Review Jury");check("all topics score at least 85",generated.every(item=>item.contentQuality.total>=85));check("all topics expose at least five axes",generated.every(item=>item.contentQuality.signals.axisCount>=5));check("all activities reference their story",generated.every(item=>item.session2.activity.sourceRef===item.session1.story.id));check("test generation leaves operational storage untouched",await page.evaluate(()=>localStorage.getItem("tb_talkflow_v1"))===before);const malformed=structuredClone(generated[0]);malformed.session2.activity.phrases=[];delete malformed.leader.story;check("malformed imported content fails closed",await page.evaluate(item=>!TalkFlow.generation.evaluate(item).ready,malformed));check("Simple lifecycle is not marked legacy",await page.evaluate(item=>TalkFlow.lifecycle(item).key!=="invalid",generated[0]));check("public viewer supports Simple topics",await page.evaluate(item=>{const html=TalkFlow.viewerHtml({[item.date]:item});return html.includes("SIMPLE CONVERSATION")&&html.includes("session1.easyTalk")},generated[0]));
for(let index=0;index<generated.length;index++){const topic=generated[index];topic.quality={status:"approved",score:100,issues:[]};topic.operatorStatus.reviewStatus="approved";await page.evaluate(item=>localStorage.setItem("tb_talkflow_v1",JSON.stringify({[item.date]:item})),topic);await page.goto(`http://127.0.0.1:${server.address().port}/?date=${topic.date}&view=print`,{waitUntil:"networkidle"});check(`${topic.generationRequest.keyword}: two pages`,await page.locator(".simple-handout .a4-page").count()===2);check(`${topic.generationRequest.keyword}: page sections`,await page.locator(".simple-page-1>.simple-section").count()===4&&await page.locator(".simple-page-2>.simple-section").count()===4);const metric=await page.locator(".simple-handout .a4-page").evaluateAll(nodes=>nodes.map(node=>({v:node.scrollHeight-node.clientHeight,h:node.scrollWidth-node.clientWidth})));check(`${topic.generationRequest.keyword}: no overflow`,metric.every(item=>item.v<=1&&item.h<=1),JSON.stringify(metric));const print=await page.evaluate(item=>TalkFlow.evaluateRenderedPrint(item),topic);check(`${topic.generationRequest.keyword}: print floors`,print.status==="ready",JSON.stringify(print));const pdf=await page.pdf({path:join(pdfDir,`student-${index+1}.pdf`),format:"A4",printBackground:true,preferCSSPageSize:true,margin:{top:"0",right:"0",bottom:"0",left:"0"}});check(`${topic.generationRequest.keyword}: PDF two pages`,(await PDFDocument.load(pdf)).getPageCount()===2);await page.addStyleTag({content:".topbar,.daily-nav,.leader-toolbar,.print-toolbar{display:none!important}"});for(let pageIndex=0;pageIndex<2;pageIndex++)await page.locator(".simple-handout .a4-page").nth(pageIndex).screenshot({path:join(evidence,`student-${index+1}-page-${pageIndex+1}.png`)})}
for(const field of ["phrases","leader","reset"]){const mutant=structuredClone(generated[0]);if(field==="phrases")mutant.session2.activity.phrases=[];if(field==="leader")delete mutant.leader.story;if(field==="reset")delete mutant.session2.reset;check(`fail-closed ${field}`,await page.evaluate(item=>!TalkFlow.generation.evaluate(item).ready,mutant))}const viewer=await page.evaluate(item=>TalkFlow.viewerHtml({[item.date]:item}),generated[0]),viewerPage=await context.newPage();await viewerPage.setContent(viewer,{waitUntil:"load"});check("public viewer executes Simple topic",await viewerPage.getByRole("heading",{name:"Can We Trust Online Reviews?"}).count()===1&&await viewerPage.getByText("TODAY’S ACTIVITY",{exact:false}).count()>=1);await viewerPage.close();const leader=generated[0];await page.evaluate(item=>localStorage.setItem("tb_talkflow_v1",JSON.stringify({[item.date]:item})),leader);await page.goto(`http://127.0.0.1:${server.address().port}/?date=${leader.date}&view=student`,{waitUntil:"networkidle"});check("normal Student view routes Simple renderer",await page.locator("#student-view .simple-handout").count()===1);await page.goto(`http://127.0.0.1:${server.address().port}/?date=${leader.date}&view=leader`,{waitUntil:"networkidle"});check("normal Leader view routes Simple renderer",await page.locator("#leader-view .simple-leader-handout").count()===1);await page.evaluate(item=>{document.body.innerHTML=`<div class="print-view"><div class="paper-stack">${TalkFlow.renderForTest(item,true)}</div></div>`},leader);check("leader renderer uses Simple design",await page.locator(".simple-leader-handout .simple-leader-note").count()>=4);const leaderPdf=await page.pdf({path:join(pdfDir,"leader-online-review.pdf"),format:"A4",printBackground:true,preferCSSPageSize:true,margin:{top:"0",right:"0",bottom:"0",left:"0"}});check("leader PDF two pages",(await PDFDocument.load(leaderPdf)).getPageCount()===2);await page.locator(".simple-leader-handout .a4-page").first().screenshot({path:join(evidence,"leader.png")});await page.evaluate(item=>localStorage.setItem("tb_talkflow_v1",JSON.stringify({[item.date]:item})),leader);
const secondLeader=generated[2];await page.evaluate(item=>{document.body.innerHTML=`<div class="print-view"><div class="paper-stack">${TalkFlow.renderForTest(item,true)}</div></div>`},secondLeader);const secondLeaderPdf=await page.pdf({path:join(pdfDir,"leader-work-group-chat.pdf"),format:"A4",printBackground:true,preferCSSPageSize:true,margin:{top:"0",right:"0",bottom:"0",left:"0"}});check("second leader PDF two pages",(await PDFDocument.load(secondLeaderPdf)).getPageCount()===2);for(const width of [375,768,1280]){await page.setViewportSize({width,height:900});await page.goto(`http://127.0.0.1:${server.address().port}/?date=${leader.date}&view=admin`,{waitUntil:"networkidle"});check(`${width}px no horizontal overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1));await page.screenshot({path:join(evidence,`admin-${width}.png`),fullPage:true})}check("console error zero",errors.length===0,errors.join(" | "));await mkdir(join(root,"artifacts"),{recursive:true});const review=["# Simple Conversation 콘텐츠 검수 보고서","","검증 세트: 8개 일반 토픽 · 학생 PDF 8개 · 리더 PDF 2개","",...generated.flatMap((topic,index)=>[`## ${index+1}. ${topic.title.en} / ${topic.title.ko}`,"",`- Story 요약: ${topic.session1.story.ko.join(" ")}`,`- Easy Talk: ${topic.session1.easyTalk.map(item=>item.en).join(" / ")}`,`- Real Talk: ${topic.session1.realTalk.map(item=>item.en).join(" / ")}`,`- Today’s English: ${topic.session1.expressions.map(item=>`${item.en} [${item.useIn.join(", ")}]`).join(" / ")}`,`- Activity: ${topic.session2.activity.name}`,`- Group Result: ${topic.session2.groupResult.en}`,`- Final Question: ${topic.session2.finalQuestion.en}`,`- 질문 axis: ${[...topic.session1.easyTalk,...topic.session1.realTalk].map(item=>item.axis).join(", ")}`,`- Story–Activity 연결: ${topic.session2.activity.sourceRef} → ${topic.session1.story.id}`,`- 콘텐츠 품질 점수: ${topic.contentQuality.total}/100 (${Object.entries(topic.contentQuality.scores).map(([key,value])=>`${key} ${value}`).join(", ")})`,`- 발견·수정한 문제: ${topic.contentQuality.warnings.length?topic.contentQuality.warnings.map(item=>item.message).join(" / "):"치명 오류 없음"}`,""] )];await writeFile(join(root,"artifacts","simple-content-review.md"),review.join("\n"));const report={pass:true,checks:checks.length,generatedAt:new Date().toISOString(),pdfDir,evidence,topics:generated.map(topic=>({date:topic.date,title:topic.title,score:topic.contentQuality.total,axes:topic.contentQuality.signals.axisCount,activity:topic.session2.activity.name,sourceRef:topic.session2.activity.sourceRef})),results:checks};await writeFile(join(evidence,"report.json"),JSON.stringify(report,null,2));console.log(`simple-qa: PASS (${checks.length} checks)`)}finally{await browser.close();server.close()}
